2단계 - 성능 테스트
next-step/infra-subway-monitoring pull request #115
Opened 2021-12-06 16:31 UTC by ungseokchoi

## 안녕하세요. 6주차 서비스 진단하기 미션 참여자 최웅석입니다. 😊

> 안녕하세요. 동환님😄 
1단계에서 질문 드린 내용에 대해서 상세한 코멘트 감사합니다.🙇
알려주신 내용 관련해서 이것저것 찾아봤지만 모두 처음 보는거라 어렵네요😰

### ⭐  2단계 학습하며 궁금한 점
> 웹 성능 테스트를 해보니 거의 대부분 css 혹은 javascript 부분이 문제가 되는데
그럼 백엔드 부분의 성능 테스트는 k6 과 같은 부하 테스트 로만 진행을 해야하는건가요??

##
> **그럼 2단계 리뷰 잘부탁드립니다. :):pray:**

2021-12-08 13:56 UTC, na-mul requested changes
안녕하세요, 웅석님
리뷰가 늦어진 점 양해해주셔서 정말 감사드립니다. 🙏
모쪼록 타 미션과 병행을 통해 과정 진행에 지장이 없으셨기를 바랍니다. 
몇가지 코멘트를 드려보게 되었어요! 확인하셔서 다시 request 주시면 감사하겠습니다 🙇‍♂️

2021-12-08 13:56 UTC, na-mul commented on README.md
> +     ![stress_result.png](images/stressTest_result.PNG)
테스트 모두 DB에 데이터가 들어있지 않은 상태로 실행된 것 같습니다. 

그래서 기능이 정상 작동하는지 체크하기 위한 smoke 테스트부터 
member 정보가 미존재하여 인증오류가 발생하는 바람에 유의미한 테스트가 진행되지 않은 것으로 추측됩니다.
(로그인 API에 대한 기능 점검인데 모든 요청이 실패가 된 것으로 결과가 나타나여 그렇게 짐작해보았습니다.)

또한 load, stress 테스트 모두 속도나 부하를 체크하기 이전에, 데이터 미존재 등으로 정상적인 API 로직 수행이 이뤄지지 않은 것으로 보입니다. 

괜찮으시면 DB 등에 데이터를 채워, 정상적인 어플리케이션 상태로 재차 테스트하기를 부탁드립니다. 🙇‍♂️

2021-12-08 13:56 UTC, na-mul commented on README.md
> +> 그러므로 웹 성능 확인 사이트에서 85~90 점 이상이 되야 한다고 생각합니다.
한번 경쟁 사이트들에도 웹 성능 확인 결과를 돌려봐서 비교해보면서 기준을 정해보는 것도 좋을 것 같아요.

사실 5초라는 속도는 경우에 따라서 매우 느린 속도가 될 수 있습니다.
반대로 최단거리 노선을 검색하여 제공하는 사이트에서는 납득할만한 속도일 수도 있습니다.

그렇기에 비교에 따른 근거 확보가 의미 있을 것 같아요!

2021-12-08 13:58 UTC, ungseokchoi commented on README.md
> +     ![stress_result.png](images/stressTest_result.PNG)
제가 테스트를 하고 서버를 내렸다 올려버려서...
아이디가 사라졌나보네요😨
부하테스트를 하면 데이터가 너무 많이 쌓여서 추후에 테스트가 불가할정도인데
이럴땐 어떻게 하면 좋을까요??? 🤔

2021-12-09 03:52 UTC, nodonn commented on README.md
> +     ![stress_result.png](images/stressTest_result.PNG)
사실 보통 현업에서는 부하테스트 환경을 분리하곤 합니다. 
조직에 따라 beta, stage, qa 등 다양한 용어로 부르곤 하지요.

다만 저희의 경우는 DB만 분리하면 될 것입니다.
docker로 DB를 띄우는 만큼, 여러개의 DB를 포트를 다르게 띄워 환경을 분리하여 테스트 해보면 어떨까 합니다.

2021-12-09 03:53 UTC, na-mul commented on README.md
> +     ![stress_result.png](images/stressTest_result.PNG)
사실 보통 현업에서는 부하테스트 환경을 분리하곤 합니다.
조직에 따라 beta, stage, qa 등 다양한 용어로 부르곤 하지요.

다만 저희의 경우는 DB만 분리하면 될 것입니다.
docker로 DB를 띄우는 만큼, 여러개의 DB를 포트를 다르게 띄워 환경을 분리하여 테스트 해보면 어떨까 합니다.

2021-12-09 03:56 UTC, na-mul commented
질문에 대한 답 남겨드립니다!

> 웹 성능 테스트를 해보니 거의 대부분 css 혹은 javascript 부분이 문제가 되는데
그럼 백엔드 부분의 성능 테스트는 k6 과 같은 부하 테스트 로만 진행을 해야하는건가요??🤔

프론트엔드를 포함한 통합 성능 테스트는 `웹 성능 테스트`로 진행해야 할 것입니다.
하지만 그러면 프론트와 백의 원인이 뒤섞인 테스트 결과가 도출되게 되지요.
백엔드만 분리하여 성능을 체크하기 위해 k6를 사용한다고 생각해주시면 감사하겠습니다.
그리고 아무래도 ui를 통한 테스트로는 부하테스트가 쉽지가 않지요...

> 로그 관련해서 운영/ 개발 상황별로 관리한다고 하셨는데 관련 자료를 찾아보니
properties 로 관리할 수 있던데 혹시 logback.xml 로 관리하시는지 properties 로 관리하시는지 궁금합니다🤔

경우에 따라 다르긴 합니다만, 간단하게 설정할 때에는 properties를 사용하는 편입니다.
다만 복잡한 경우에는 xml을 사용하지요. 실제로 현업에서는 현재 xml을 사용하고 있습니다.

2021-12-09 05:33 UTC, ungseokchoi commented on README.md
> +- Keep-Alive 설정
Keep-Alive 설정 관련해서 찾아보니 nginx 와 spring properties 두가지 방법이 있던데
어디서 하는게 옳은 방향일까요?? 아무래도 tcp 통신 관련이니까 nginx 에서 하면 좋을꺼 같은데 🤔
동환님의 의견이 궁금합니다 :)

2021-12-09 08:22 UTC, na-mul commented on README.md
> +- Keep-Alive 설정
nginx에서 하는 편이 좋을 것 같습니다. 
https에 대한 설정도 스프링에서 가능하지만 nginx에 진행하는 것과 동일한 이유라고 보시면 될 것 같습니다.
더 일 잘하는 쪽에 책임을 맡기는 책임 분산이라고 볼 수 있을 것 같아요.

2021-12-09 08:23 UTC, na-mul commented on README.md
> +- Keep-Alive 설정
nginx.conf 등도 git repo에 함께 넣어서 관리하면 마치 코드처럼 버전관리를 진행할 수 있어 유용합니다. 
( 배포 후 어플리케이션 가동할 때 nginx가 해당 conf를 참고하도록 배포 단계를 설정할 필요는 있습니다. )

2021-12-13 10:23 UTC, na-mul approved these changes
안녕하세요 웅석님!
2단계를 전면적으로 재차 진행해주셔서 깔끔하게 마무리해주셨네요.
특히 고생이 많으셨습니다. 👍
그만큼 배운 것도 많으셨기를 기대하며, 과정 마무리까지 화이팅입니다.

2021-12-13 10:23 UTC, merged