🚀 2단계 - 성능 테스트
next-step/infra-subway-monitoring pull request #152
Opened 2021-12-15 15:46 UTC by vvshinevv

안녕하세요? 서비스 진단하기 마지막 단계를 하고 있는 최홍희입니다.
이번 미션은 처음 써보는 새로운 것들을 알 수 있는 시간이였습니다.
이번 리뷰도 잘 부탁드립니다.
감사합니다.

2021-12-17 01:52 UTC, leeyohan93 requested changes
2단계 미션도 잘 구현해주셨네요 👍 
성능 테스트를 할 때 조금 더 생각해보면 좋을 부분들에 대해 코멘트 남겨드렸으니 확인 부탁드릴게요 :)
리뷰 양해해주셔서 감사합니다 🙏

2021-12-17 01:52 UTC, leeyohan93 commented on README.md
> +```
부하 테스트 전제조건을 좀 더 상세하게 정해보면 어떨까요 ?
부하테스트 페이지의 `E. 테스트 계획하기`를 참고해보시면 좋을 것 같아요 :)

2021-12-17 01:52 UTC, leeyohan93 commented on README.md
> +4. Smoke, Load, Stress 테스트 스크립트와 결과를 공유해주세요
스트레스 테스트같은 경우에는 아래와 같이 최대 사용자나, 최대 사용량까지 확인하는 작업이 더해지면 좋을 것 같습니다 :)
참고만 해주셔도 좋습니다 🙏 

- 서비스가 극한의 상황에서 어떻게 동작하는지 확인합니다.
- 장기간 부하 발생에 대한 한계치를 확인하고 기능이 정상 동작하는지 확인합니다.
- 최대 사용자 또는 최대 처리량을 확인합니다.
- 스트레스 테스트 이후 시스템이 수동 개입없이 복구되는지 확인합니다.

2021-12-18 14:14 UTC, vvshinevv commented on README.md
> +4. Smoke, Load, Stress 테스트 스크립트와 결과를 공유해주세요
조언 감사드립니다. 🤗

2021-12-19 00:50 UTC, leeyohan93 approved these changes
코멘트 드린 전제조건을 자세하게 잘 설정해주셨네요!👍👍 이번 단계는 머지하도록 하겠습니다 🙂 다음 단계도 화이팅해주세요!🙏

2021-12-19 00:50 UTC, merged