Step1 - 로깅과 모니터링
next-step/infra-subway-monitoring pull request #155
Opened 2021-12-15 22:36 UTC by pageprologue

리뷰어님 안녕하세요🙂
서버 진단하기 미션 1단계를 진행해 보았습니다.
그동안 기본적으로 설정되어 있는 로그를 사용하고 직접 로그를 설정하는 방법에 대해 잘 알지 못해서 생각보다 미션이 어려웠습니다..!
그래도 이번 기회에 배워갈 수 있어서 도움이 많이 되었습니다. 
aop도 학습하면서 적용해 보았는데 더 깊이 공부해서 앞으로 잘 사용하도록 해야겠습니다~!
cloudwatcheh 이번에 처음 사용해 봤는데 정말 좋은 것 같습니다.🤭

그리고 한 가지 문제가 있는데요..!
제가 web1과 web2 라는 외부망 EC에 cloudwatch 를 설치할 때 설정을 잘못 입력해서 web2에서 amazon-cloudwatch-agent 가 시작이 되지 않고 있습니다. 이 부분은 조금 같이 봐 주셨으면 좋겠습니다..😭

2021-12-16 10:38 UTC, kang-hyungu commented
web2에서 어떤 설정을 잘못하신 건지 찾지를 못하겠네요
config-downloader 실행할 때 common-config.toml을 못찾는 걸로 나오는데 관련 설정을 하셨다면 삭제해보시기 바랍니다.
설정 히스토리를 파악하기 힘들다면 web2 서버를 새로 띄우는 방법도 있겠네요.

2021-12-16 10:40 UTC, kang-hyungu requested changes
희진님
로그 남지 않는 부분만 다시 확인해서 리뷰 재요청 주시면 머지 처리하겠습니다.

2021-12-16 16:01 UTC, pageprologue commented
현구님 안녕하세요.🙂
어제 계속 `common-config.toml` 이 파일을 못찾는 오류를 해결하려고 aws 파일을 지우고 여러번 다시 설치를 시도했었는데 잘 안 됐었습니다.
amazon-cloudwatch-agent 를 깨끗하게 제거하지 못하더라구요,, 차라리 이렇게 인스턴스를 지우고 다시 생성하는게 더 빠르네요..!
말씀해주신 대로 처리해서 오히려 속이 시원합니다..ㅎㅎ 
그리고 web1에도 amazon-cloudwatch-agent status가 `"configstatus": "not configured"` 로 나왔었는데 문제의 `common-config.toml` 파일을 복사해서 넣어주니 이 부분도 고쳐지네요~! 열어보니 파일이 다 주석으로 되어 있더라구요..ㅎㅎ;;
감사합니다👍

2021-12-17 02:20 UTC, kang-hyungu approved these changes
희진님 미션 진행 잘 해주셨습니다.
원인 파악하느라 고생 많으셨어요.
pr은 머지 처리할게요 다음 단계 진행해주세요.

2021-12-17 02:21 UTC, merged