[2단계 - 성능테스트] 코드 리뷰 부탁드립니다.
next-step/infra-subway-monitoring pull request #19
Opened 2021-06-20 18:22 UTC by realizeme

2021-06-21 11:26 UTC, brainbackdoor requested changes
안녕하세요~ 미션 잘 진행해주셨네요! 몇가지 궁금한 점들 피드백에 추가해두었는데요
3주차 미션 진행하면서 함께 반영부탁드려요~ 🙏🏻
좋은 밤 보내세요! 👋🏻

2021-06-21 11:26 UTC, brainbackdoor commented on README.md
> +- Largest Contentful Paint: 1.502s
혹시 FCP 예산을 2초로 산정한 이유가 있으실까요?

2021-06-21 11:26 UTC, brainbackdoor commented on README.md
> +  |Latency|100ms |
DAU가 100,000 이면, 1일 총 접속수는 50,000, 1일 평균 rps는 5.78 정도인데요.
1일 최대 rps가 어떻게 49가 되는걸까요?
그리고 예상 1일 사용자 수는 어느정도를 기준으로 산정하신걸까요? 목표치가 낮아서 부하테스트가 크게 의미없을거 같긴 하네요 😅

2021-06-21 11:26 UTC, brainbackdoor commented on README.md
> +      http_reqs......................: 22398   37.30579/s
목표 rps에 맞춰 VUser를 도출해보는 건 어떨까요

2021-06-21 11:26 UTC, brainbackdoor commented on README.md
> +      http_reqs......................: 68558  206.896746/s
VUser 800, rps 206 지점에서 장애가 발생했을까요?

2021-06-21 11:26 UTC, brainbackdoor commented on README.md
> +      { expected_response:true }...: avg=14.31ms  min=3.48ms med=10.79ms max=3.6s     p(90)=25.3ms  p(95)=33.4ms
max 3초가 넘어가는데 테스트가 통과하네요.
목표 latency는 100ms 아니었나요?

2021-06-21 11:27 UTC, brainbackdoor approved these changes
아이고 잘못눌러 다시 Approve 해요~

2021-06-21 11:27 UTC, merged

2021-06-22 03:51 UTC, realizeme commented on README.md
> +- Largest Contentful Paint: 1.502s
어떻게 정해야 할지 몰라서 3초 법칙으로 기준으로 정했습니다. 혹시 어떻게 정하면 좋은 방향성을 가질 수 있을까요?

2021-06-22 04:12 UTC, realizeme commented on README.md
> +  |Latency|100ms |
제가 실수했네요.  제대로 이해를 못해서 계산도 실수한거 같습니다.

DAU -> 100,000
평균 RPS -> 5.78 (600,000/86400)
1일 최대 -> 100000*0.7(70%)/3600 = 19.4 RPS

의미있는 RPS를 계산해 본적이 없어서 그런데.. 보통 어떻게 Budget을 잡아야 의미가 있을까요? 아직은 추상적이네요.

2021-06-22 04:23 UTC, realizeme commented on README.md
> +      { expected_response:true }...: avg=14.31ms  min=3.48ms med=10.79ms max=3.6s     p(90)=25.3ms  p(95)=33.4ms
네 100m를 목표로 지정했습니다. 말씀하신 대로 라면  latency는 max가 기준인가요?

2021-06-22 05:45 UTC, realizeme commented on README.md
> +      http_reqs......................: 68558  206.896746/s
disk 용량 때문에 발생한 오류가 생각됩니다.

2021-06-22 09:05 UTC, realizeme commented on README.md
> +- Largest Contentful Paint: 1.502s
3초 적은 수(3초 법칙에 따라)를 찾다가 2초 정도로 정했습니다. 예산 산정 시에 어느 정도가 좋을지 몰랐습니다. 올바른 가이드가 있을까요?

2021-06-22 09:26 UTC, realizeme commented on README.md
> +      { expected_response:true }...: avg=14.31ms  min=3.48ms med=10.79ms max=3.6s     p(90)=25.3ms  p(95)=33.4ms
p99를 2초로 설정해서 그런거 같습니다.  이와 같은 지표는 어떻게 해석하는게 맞나요?
p99와  max와의 차이가 큰 건? queue이 오래되고 처리되었다고 생각하면 될까요?