Rkdals213 step1
next-step/infra-subway-monitoring pull request #213
Opened 2022-03-24 12:05 UTC by rkdals213

처음에 ngrinder를 시도해보다 결국 계속되는 에러로 이번에는 실패했네요.  그래도 이번에 간단한 테스트정도는 성공해서 다음에 환경구축을 제대로 할 수 있는 기회가 왔을때 다시 시도해봐야겠습니다.

테스트를 수행하다 ec2의 메모리가 가득 차버리는 이슈가 있었습니다.  부하를 많이 주면서 반복적인 테스트를 해서 이렇게 된건진 모르겠지만 퍼블릭 ec2를 다시 세팅해서 일단 미션을 진행했습니다.

2022-03-25 11:42 UTC, brainbackdoor commented
아, ngrinder 로 결과치를 공유주실 줄 알았는데 아쉽네요.
다음 강의 때는 ngrinder 소개자료도 추가해둬야겠네요; 사실 그렇게 어렵진 않거든요.
강의 끝나고 한번 또 시도해보세요. 본질은 같아서 인사이트를 얻는게 있지는 않겠지만, 현업에서 많이들 쓰셔서 현업에서 부하테스트를 할 때는 ngrinder 로 구축하고 진행하실듯해요.

2022-03-25 11:42 UTC, brainbackdoor requested changes
1단계 미션 잘 진행하셨네요! 
스트레스 테스트 개념을 오해하신듯 해서 피드백 남겨두었어요~

2022-03-25 11:42 UTC, brainbackdoor commented on README.md
> +![test](/images/stress.png)
Stress Test 는 peak 시간대에 대한 테스트가 아니에요.
부하테스트를 할 때 평소 트래픽과 피크시간대에 대해 테스트를 해야 하는거고,
Stress Test는 점진적으로 부하를 늘려가면서 현재 서비스의 latency가 언제 급증하는지, tps 가 언제 떨어지는지를 체크하기 위해 진행해요.

2022-03-26 07:17 UTC, rkdals213 commented
> 아, ngrinder 로 결과치를 공유주실 줄 알았는데 아쉽네요. 다음 강의 때는 ngrinder 소개자료도 추가해둬야겠네요; 사실 그렇게 어렵진 않거든요. 강의 끝나고 한번 또 시도해보세요. 본질은 같아서 인사이트를 얻는게 있지는 않겠지만, 현업에서 많이들 쓰셔서 현업에서 부하테스트를 할 때는 ngrinder 로 구축하고 진행하실듯해요.

2022-03-26 07:20 UTC, rkdals213 commented
테스트 방법에대해 제가 오해를 했었네요.  해당부분 다시 테스트해보았습니다.

그리고 k6도 그라파나를 통해 그래프화시켜주는 오픈소스가 있어서 같이 사용해보았습니다

2022-03-26 10:46 UTC, brainbackdoor approved these changes
1단계 미션 진행하느라 고생하셨어요! 👍🏻 
k6 결과 데이터를 그라파나로 보니 더 직관적이고 좋네요. 💯 
2단계 미션도 다양한 시도 해보시길 바래요 🙏🏻

2022-03-26 10:46 UTC, brainbackdoor commented on README.md
> +![test](/images/load-grafana.png)
👍🏻 
오 그라파나로도 볼 수 있군요. 공유 감사합니다.
그라파나로 보니 더 직관적으로 확인할 수 있네요

2022-03-26 10:46 UTC, merged