Step2: 화면응답 개선하기
next-step/infra-subway-monitoring pull request #223
Opened 2022-03-30 06:39 UTC by yunhalee05

화면응답 개선하기 미션 2단계를 구현하였습니다!

✔️ 정확한 계산으로 목표값을 재설정 (latency, rps 등)
✔️ 1단계 피드백 반영 (k6 grafana결과값 추가)
✔️ revers proxy 개선 (gzip, http2, cache, 부하분산 적용)
✔️ redis를 이용한 WAS 개선 (path부분에 적용)
✔️ 각 케이스 별로 Smoke, Load, Stress 테스트 결과 기록
✔️ 성능 개선 이전과 이후 비교 

감사합니다!!🙌

2022-03-30 20:42 UTC, brainbackdoor requested changes
2단계 미션도 잘 진행하셨네요~ 👍🏻 
몇가지 궁금한 점이 있어 Comment 남겼어요~
좋은 하루 보내요! 👋🏻

2022-03-30 20:42 UTC, brainbackdoor commented on README.md
> +- 평균 VUser = (78.125 * 0.3)/4 = 5.8593 -> 6
R이 3으로 변경되었는데 그대로 4로 나누었네요..?

2022-03-30 20:42 UTC, brainbackdoor commented on README.md
> +[**WebPageTest결과**](https://www.webpagetest.org/result/220330_BiDcG3_42P/)
ngrinder 의 경우 VUser 는 목표 값과 다르군요?
그리고 tps 가 안오르는데요. agent 를 더 생성하셔야 할듯해요. 혹시 단일 머신에서 돌리고 있다면 스케일아웃을 해야 할듯해요

2022-03-30 20:42 UTC, brainbackdoor commented on README.md
> +![stress 테스트 결과](https://user-images.githubusercontent.com/63947424/160753997-eb3b08c3-2a0e-41e9-8fd9-21b4777fb7d5.png)
음..? 왜 전반적으로 성능 개선 이후에 응답시간이 더 길어졌지요..?

2022-03-31 15:55 UTC, yunhalee05 commented on README.md
> +![stress 테스트 결과](https://user-images.githubusercontent.com/63947424/160753997-eb3b08c3-2a0e-41e9-8fd9-21b4777fb7d5.png)
해당 부분 정확한 수치를 반영하여 성능개선 전 후 테스트를 다시 진행하였습니다! 나머지 응답시간은 향상된 결과를 보였으나 main load 테스트 0.11ms, main stress 테스트 2.56ms,  path load 테스트 0.01ms, update stress 테스트 0.86ms 정도 늘어난 결과를 보였습니다 😭

2022-03-31 15:55 UTC, yunhalee05 commented on README.md
> +[**WebPageTest결과**](https://www.webpagetest.org/result/220330_BiDcG3_42P/)
해당 부분 변경하고 테스트를 다시 진행하였습니다! agent 를 추가하여 tps 상승한 것을 확인할 수 있도록 하였습니다!

2022-03-31 15:55 UTC, yunhalee05 commented on README.md
> +- 평균 VUser = (78.125 * 0.3)/4 = 5.8593 -> 6
해당 부분 변경하고 테스트를 다시 진행하였습니다! 죄송합니다😭

2022-04-05 23:27 UTC, brainbackdoor commented on README.md
> +![stress 테스트 결과](https://user-images.githubusercontent.com/63947424/160753997-eb3b08c3-2a0e-41e9-8fd9-21b4777fb7d5.png)
혹시 Scale out 을 더 늘려서도 테스트 해보셨을까요?
단일 요청에 대해 문제가 없는데, 부하를 늘릴 경우 지연시간이 높아진다면,
처리해야 할  Task가 늘어나서 발생하여 처리하지 못하는 경우가 생겨서라요.

2022-04-05 23:27 UTC, brainbackdoor commented on README.md
> +![stress 테스트 결과](https://user-images.githubusercontent.com/63947424/160753997-eb3b08c3-2a0e-41e9-8fd9-21b4777fb7d5.png)
혹시 Scale out 을 더 늘려서도 테스트 해보셨을까요?
단일 요청에 대해 문제가 없는데, 부하를 늘릴 경우 지연시간이 높아진다면,
처리해야 할  Task가 늘어나서 발생하여 처리하지 못하는 경우가 생겨서라요.

2022-04-05 23:27 UTC, brainbackdoor approved these changes
피드백 반영 잘해주셨네요. Scale out 과 관련해서 Comment 남겨뒀으니, 추후에 다시 한번 테스트해보셔요~

2022-04-05 23:28 UTC, merged