Step2 : 부하 테스트
next-step/infra-subway-monitoring pull request #346
Opened 2022-06-20 10:46 UTC by mannue

안녕하세요 
바쁘신 가운데 리뷰 해주셔서 감사합니다.

결과물은 subordinate/result 안에 메인페이지, path 가져오는 페이지, 역정보 가져오는 페이지 별로 결과물은 저장하였습니다.

오늘 하루도 좋은 하루되세요
감사합니다~

2022-06-20 17:41 UTC, chae-yh requested changes
은남님 안녕하세요! 환경 구성 및 성능 테스트 잘 해주셨습니다 👍 다만 바로 merge 하기에는 조금만 더 고민해보시면 좋을 만한 내용이있어 코멘트 드리니 확인 부탁드립니다!

감사합니다 : )

2022-06-20 17:41 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/LineRepository.java
> +    @Query(value = "SELECT * FROM line", nativeQuery = true)
헙.. 이것도 고쳐주셨군요 ㅎ.ㅎ;;; 
사실 다음 step의 과제입니다만... 잘 수정해주셨습니다 👍

2022-06-20 17:41 UTC, chae-yh commented on docs/README.md
> +  - [x] Smoke, Load, Stress 테스트 후 결과를 기록
요구 사항 작성 및 체크해주셨네요. 좋습니다 👍

2022-06-20 17:41 UTC, chae-yh commented on README.md
> +        - 18.5 * 1.6 = __29.6rps__
peck 의 rps 잘 구해주셨네요 👍

2022-06-20 17:41 UTC, chae-yh commented on README.md
> +        - Latency : 50ms
참조한 데이터에서 rps를 구하는 논리가 자연스럽네요 👍

2022-06-20 17:41 UTC, chae-yh commented on docker/docker-compose.yml
> +    platform: linux/amd64
혹시 이 부분 수정 하신 이유를 여쭤봐도 될까요...?

2022-06-20 17:41 UTC, chae-yh commented on subordinate/script/load/main_load.js
> +        { duration: '10s', target: 0 },
load test의 경우는 강의에서도 아래와 같이 언급하였듯,
`서비스의 평소 트래픽과 최대 트래픽 상황에서 성능이 어떤지 확인합니다. 이 때 기능이 정상 동작하는지도 확인합니다.`
평소, 최대 트래픽의 상황에서의 성능 테스트입니다. 작성해주신 16은 최대 트래픽에서의 성능 테스트로 보이는데, 평소일 때부터 최대일 때까지 트래픽이 변경되는 것을 같이 테스트 해주면 어떨까요...?

2022-06-20 17:41 UTC, chae-yh commented on subordinate/script/stress/main_stress.js
> +        { duration: '10s', target: 0 },
stress test 는 강의에서도 나왔듯, 서비스가 극한의 상황에서 어떻게 동작하는지를 확인하고 최대 처리량 혹은 최대 사용자를 확인 과 장애 상황에서 복구했을 경우 기능이 수동 개입 없이 자동으로 복구되는지 를 확인하는 테스트입니다.
현재 부하를 적절하게 주셨습니다만, 실제 실패율(http_req_failed)은 높지 않은 케이스가 존재합니다.
조금 더 장기간에 강한 부하를 주고, 해당 시스템이 자동으로 복구되는지를 확인해보는 것은 어떨까요...?
테스트 관련하여 참고해보시면 좋을 만한 내용 관련하여 링크드립니다!
https://techblog.woowahan.com/2572/
https://www.softwaretestinghelp.com/what-is-performance-testing-load-testing-stress-testing/

2022-06-21 01:10 UTC, mannue commented on src/main/java/nextstep/subway/line/domain/LineRepository.java
> +    @Query(value = "SELECT * FROM line", nativeQuery = true)
안녕하세요 ^^
음 이부분 안고치면 기능이 작동안되어서 수정하였습니다 ㅠㅠ

2022-06-21 01:10 UTC, mannue commented on docs/README.md
> +  - [x] Smoke, Load, Stress 테스트 후 결과를 기록
감사합니다 👍

2022-06-21 01:23 UTC, mannue commented on subordinate/script/load/main_load.js
> +        { duration: '10s', target: 0 },
조언 감사합니다.
```text
        { duration: '15m', target: VU },
        { duration: '15m', target: MAX_VU },
        { duration: '10s', target: 0 },
```

평균 유저와 최대 유저로 변경해서 해보겠습니다. 감사합니다 👍

2022-06-21 01:24 UTC, mannue commented on subordinate/script/stress/main_stress.js
> +        { duration: '10s', target: 0 },
정보까지 공유 해주셔서 감사합니다.
읽어 보고 stress 관련해서 수정하겠습니다 ^^

2022-06-21 17:46 UTC, chae-yh approved these changes
은남님 안녕하세요! 피드백 반영 잘해주셨습니다 💯 이번 step의 목적은 달성해 주셨기에, merge 하겠습니다!

이제 마지막 step만 남았네요! 다음 step 진행 부탁드립니다 : )

2022-06-21 17:46 UTC, chae-yh commented on docker/docker-compose.yml
> +    platform: linux/amd64
m1 macbook 이슈인가보네요! m1 에서 안돌아가는게 리소스나 라이브러리가 종종 보이네요 ㅎ.ㅎ;;

2022-06-21 17:46 UTC, merged