2단계 - 부하테스트
next-step/infra-subway-monitoring pull request #348
Opened 2022-06-20 15:52 UTC by handh0413

영훈 리뷰어님 안녕하세요!  😀
우선 지난 번 미션 [리뷰](https://github.com/next-step/infra-subway-monitoring/pull/318) 감사드립니다.
리뷰 달아주신 내용 관련하여 고민한뒤 피드백 반영 하였습니다!

이번 미션은 처음 접해보는게 많아서 많은 시행착오를 겪었습니다.. 😢
제가 구축한 시스템을 제 손으로 장애를 발생시켜야 하는 미션이라 더욱 힘들었습니다.
하지만 시스템의 한계를 테스트해보는 과정에서 많은 것을 배운 것 같네요 ㅎㅎ

그럼 2단계 관련하여 시간 여유 되실 때 미션 부탁드립니다. 🙏
감사합니다!

2022-06-20 17:27 UTC, chae-yh requested changes
동희님 안녕하세요! step1의 피드백까지 잘 반영해주시고, 환경 구성 및 테스트도 잘 진행해주셨습니다 👍 다만 조금만 더 고민해보시면 좋을만한 내용이 있어 코멘트 드리니 확인 부탁드립니다!

감사합니다 : )

2022-06-20 17:27 UTC, merged

2022-06-21 15:38 UTC, handh0413 commented on k6/load/load.js
> +        http_req_duration: ['p(99)<1500'], // 99% of requests must complete below 1.5s
처음에는 1.5초를 기준으로 k6 테스트를 진행하면서 목표(100ms)로 줄여가면서 테스트해보려고 했는데요,
막상 k6 테스트를 수행해보니 처음에 제가 예상했던 것보다 속도가 많이 느렸습니다.. 😢
load 테스트에서 http_req_duration(p95)가 3.17초가 나왔으며, stress 테스트에서는 23.08초가 나오게 되면서
차마 값을 늘리진 못하고 그대로 두게 되었습니다...

2022-06-21 16:28 UTC, handh0413 commented on k6/stress/stress.js
> +import http from 'k6/http';
좋은 내용 리뷰 및 공유해주셔서 감사합니다!
내용을 하나씩 확인해보니 0.36%의 실패율 가지고는 최악의 상황에서 시스템을 검증했다고 볼 수 없을 것 같으며,
시스템이 자동으로 복구될 수 있다고 말하기에는 부족한 것 같습니다! 
시스템을 제대로 검증할 수 있는 stress 테스트를 추가로 진행해봐야 할 것 같습니다 👍

2022-06-21 16:28 UTC, handh0413 commented on README.md
> +### 2. Smoke, Load, Stress 테스트 스크립트와 결과를 공유해주세요
감사합니다!

2022-06-21 16:31 UTC, handh0413 commented on README.md
> +    - (6 * 0.1) + 1 = 2s
지하철 이용 관련하여 `집중률(최대 트래픽 / 평소 트래픽)`이 저의 생각보다 낮아서 당황했습니다.
그러다보니 VUser를 조금이라고 높이기 위해서 소수 점 이하는 올림 처리로 진행하였습니다.