[6주차 1단계] 로깅과 모니터링
next-step/infra-subway-monitoring pull request #36
Opened 2021-06-27 11:33 UTC by AppleMango2021

리뷰어님 안녕하세요!
우아한 테크캠프 Pro 2기 수강생 이지선입니다. 

1단계 미션 완료하여 리뷰 요청드립니다. 
지난 4주차 미션 때 사용하였던 Web 서버를 사용하였고, Web 서버 내부에 Docker를 이용하여 Nginx 서버 구성하였습니다. 

애플리케이션 로그 남길 때에는 AOP를 활용하였는데, 좋은 선택이었는지는 사실 잘 모르겠습니다. `Exception` 발생 시, 바로 `@ExceptionHandler`에 걸리지 않아 `@Aspect` 클래스에서 다시 `Exception`을 던져주거나 `Controller`단에서 에러처리를 다시 해야 하는 문제가 있었습니다. 저는 후자의 방법을 사용하였는데, 어느 방법을 사용하든 불필요한 로직을 탄다는 느낌을 받았습니다. 

로그는 회원가입, 로그인, 경로탐색 세 가지 메소드에 한해서 남겼고,  `CloudWatch`와 `Spring Boot Actuator`를 통해서 대시보드 구성하였습니다.

감사합니다.

2021-06-28 00:35 UTC, young891221 commented
말씀하신데로 AOP로 로그를 남기는것은 좋은 선택지가 아닙니다.
AOP 자체가 서버 리소스를 많이 잡아 먹고 서버 부팅시에도 로그 관련 페키지를 모두 탐색하고 띄워야 하기에 부팅시간도 오래걸립니다. 때문에 저는 filter를 사용하는 방법을 추천드리고 있습니다.
다만, 스프링에서 request body의 byte코드를 한번만 읽는것으로 제한하기에 커스텀하게 만들어 캐싱된 객체를 반환하는 방식을 사용해야 합니다. (https://taetaetae.github.io/2019/06/30/controller-common-logging)
이게 좀 까다로운 방식이여서 실무에서는 적용하셔야 겠지만...연습 프로젝트에서 하고 넘어갈지는 본인이 판단해서 진행해 주세요ㅎ

2021-06-28 00:43 UTC, young891221 requested changes
안녕하세요, 지선님
로깅환경 구성 및 클라우드와치 셋팅 잘 해주셨네요 👍 
의문점에 대한 답변과 한 가지 코멘트 드렸습니다. 확인 부탁드려요:)

2021-06-28 00:43 UTC, young891221 commented on src/main/resources/logback.xml
> +    <logger name="console" level="TRACE" >
무조건 TRACE 레벨로 남기면 로그가 엄청남게 되어 용량이 금방 찰 수 있습니다.
로컬이나 prod 환경에 따라 로그 레벨을 다르게 부여해 주세요.
![1](https://user-images.githubusercontent.com/15729299/123564566-e17d2800-d7f4-11eb-89fc-2f4824961d7e.PNG)

2021-06-30 15:44 UTC, AppleMango2021 commented
경준님 안녕하세요. 지난번 리뷰 요청 드릴 때, `README.md` 파일 수정한 커밋을 푸쉬하지 않았었네요 ㅠㅠ 찾느라 번거로우셨을텐데 죄송합니다. 

피드백 주신대로 개발환경에 따라 로깅레벨을 다르게 주었습니다. 운영의 경우, 파일에는 `WARN` 레벨 이상부터 남기도록 두었는데, 실제 운영 환경에서는 통상적으로 어떻게 설정하는지 궁금합니다. 

그리고 남겨주신 AOP 링크는 확인해보았는데, 바로 적용하기에는 공부해야 할 부분이 많아 이번 미션에서는 현재 AOP 방식을 유지하도록 하겠습니다.

2021-07-01 07:31 UTC, young891221 approved these changes
리뷰 반영 감사합니다.
2단계 진행해 주세요!ㅎ

2021-07-01 07:31 UTC, merged