[1단계 - 로깅과 모니터링] 리뷰 요청 드립니다!
next-step/infra-subway-monitoring pull request #37
Opened 2021-06-27 15:37 UTC by itdar

안녕하세요, 리뷰어님. 인프라 관련이 항상 어려운것 같습니다..ㅎㅎ

++ 풀리퀘스트를 날렸었다가, 빠진 내용 (nginx access.log, error.log 설정) 이 있어서 재설정 후 다시 풀리퀘스트 만듭니다.
혹시 서버로 직접 들어가보실 일이 있다면, admin (13.209.73.178:22) 열어두어서, 그 안에서 ssh 로 다른 모두 접근 가능합니다!

- 일단 로그는 꼭 필요한 로깅이 정해져있다면 필요한 부분만 logger 만들어서 로그 찍는 것이 더 나을수도 있을 것 같았습니다만.. aop 를 써보고 싶어서 여러 방법으로 around 와 pointcut으로 범위를 지정해보기도 하고 어노테이션을 사용하기도 했습니다.
- 인프라는 항상 익숙하지 않아서 그런가.. 코드량이 많지 않고 별로 건드릴 내용이 많지 않은 것 같으면서도 막상 하려면
이것저것 공부할게 많아서 시간이 상당히 걸리네요..ㅠㅠ 기존에 구축해두었던 프록시서버와 연결된 서버에 클라우드워치 연결해두었습니다.

리뷰 잘 부탁드립니다. 감사합니다!

2021-06-29 02:19 UTC, kang-hyungu requested changes
안녕하세요 형진님, 만나서 반갑습니다. 리뷰어 강현구입니다 👋 
리뷰가 많이 늦어졌네요. 죄송합니다.
몇 가지 코멘트 남겼어요. 확인해보시고 답변 부탁드려요
궁금한 점은 dm 주시거나 코멘트 남겨주세요

2021-06-29 02:19 UTC, kang-hyungu commented on src/main/java/nextstep/subway/logback/LogAopHandler.java
> +    public Object annotationInOutJsonLogging(ProceedingJoinPoint joinPoint) throws Throwable {
아래 annotationInFileLogging 메서드와 동일한 동작을 하는 것 같은데 따로 분리한 이유가 있을까요?
어노테이션을 나누는 용도일까요?

2021-06-29 02:19 UTC, kang-hyungu commented on src/main/java/nextstep/subway/logback/LogAopHandler.java
> +    @Around("execution(* nextstep.subway.member.application.*Service.*(..))")
만약 패키지를 다시 구성하거나 서비스 레이어에 해당되는 클래스에 Service라는 이름을 사용하지 않으면 로그가 남지 않겠네요.
그리고 모든 서비스 레이어에 해당되는 객체는 입, 출력에 대한 로그를 남기는게 맞을까요?
반환 타입이 void인 경우는 문제 없을까요?

2021-06-29 02:19 UTC, kang-hyungu commented on README.md
> +c. 로그 수집
aws cloudwatch logs를 사용하도록 설정하신거죠?

아래 syslog, nginx의 access와 error log는 어디서 확인 가능할까요?
그리고 스프링 애플리케이션에서 쌓는 로그도 aws cloudwatch logs로 확인 가능할까요?

2021-06-29 02:19 UTC, kang-hyungu commented on src/main/resources/logback.xml
> +        <root level="INFO">
운영에 info 레벨로 쌓으면 로그 용량이 금방 초과될 것 같은데 어느 레벨이 적절할까요?

2021-06-29 03:02 UTC, itdar commented on src/main/java/nextstep/subway/logback/LogAopHandler.java
> +    public Object annotationInOutJsonLogging(ProceedingJoinPoint joinPoint) throws Throwable {
> 아래 annotationInFileLogging 메서드와 동일한 동작을 하는 것 같은데 따로 분리한 이유가 있을까요?
> 어노테이션을 나누는 용도일까요?

안녕하세요, 현구님 반가워요. 리뷰 감사드립니다!! ㅎㅎ
 aop로 로그를 남기는 작업을 처음해봐서 이런저런 방법으로 시도를 해보았습니다.
- 패키지의 클래스 이름 등으로 범위를 설정하는 것
- - Around 로 설정, Pointcut 으로 before/after 각각 설정
- 어노테이션으로 설정하는 것
여기서 위의 중복은 File 로거를 사용하는지, Json 로거를 사용하는지에 따른 메서드 분리였는데,
Json 로거를 사용한 이유는 경로 탐색 후, 반환 값들을 json 형식으로 반환하도록 하기 위함이었습니다!

음.. 사실 어떤게 좋은지 잘 감이 안오네요, 어떻게 생각하시나요?
아래 리뷰를 보니 일단 service / controller 등의 범위로 된 것들은 다시 생각을 해봐야겠습니다!

2021-06-29 07:10 UTC, itdar commented
> 안녕하세요 형진님, 만나서 반갑습니다. 리뷰어 강현구입니다 👋
> 리뷰가 많이 늦어졌네요. 죄송합니다.
> 몇 가지 코멘트 남겼어요. 확인해보시고 답변 부탁드려요
> 궁금한 점은 dm 주시거나 코멘트 남겨주세요

안녕하세요, 현구님. 재리뷰 요청드립니다!

 우선 syslog, nginx의 access와 error log 는 각각 /var/log/ 와 /var/log/nginx/ 에 있습니다.
admin 에서 ssh reverse-proxy 접근해서 확인 가능합니다!
admin 은 13.209.73.178 이고, 접근 전체 열어두었습니다.
아.. key 는 이전 미션에서 올려두었는데 필요하시면 말씀해주세요!

 그리고 aws cloudwatch 에서 애플리케이션의 로그도 연결 했습니다. 이름을 설정 안해서 그랬는지 ip로만 host 에 쌓이고 있었습니다. 기존에 서버-1 만 쌓도록 했었는데, 서버-2, 리버스프록시서버 까지 추가했습니다. 제대로 연결한건지 확인 부탁드립니다!

 로그를 남기는 위치나 로그 레벨에 대해서 다시 수정을 해보았습니다.
- 운영 시의 로그는 처음에 ERROR 로 하려다가, 그러면 aop로 찍으려던 코드상에서 로그를 error로 해야 찍혀서 리뷰 시 확인이 가능할 것 같아서, 로그를 info 로 하고 properties 도 INFO 로 맞춰두었었습니다. 현재 코드의 로그는 info, 운영 시 로그 properties 는 ERROR 로 수정했습니다.
- annotationInFileLogging 위에 중복된다고 하셨던 내용에 답글은 제가 착각을 했습니다. 중복이 맞습니다. 저건 제가 각 페이지들 이동 시에 로그를 찍을 방법이 있나 해서 In 으로 페이지 호출 url을 찍을 수 있나 테스트 했다가 남겨두었었네요..ㅠㅠ 지웠습니다.
- 필요한 메서드만 어노테이션으로 최소의 범위로 로그를 남기도록 했고, 불필요한 메서드들 삭제했습니다.

재리뷰 요청드립니다. 감사합니다!!!

2021-06-30 04:49 UTC, kang-hyungu commented
> > 안녕하세요 형진님, 만나서 반갑습니다. 리뷰어 강현구입니다 👋
> > 리뷰가 많이 늦어졌네요. 죄송합니다.
> > 몇 가지 코멘트 남겼어요. 확인해보시고 답변 부탁드려요
> > 궁금한 점은 dm 주시거나 코멘트 남겨주세요
> 
> 안녕하세요, 현구님. 재리뷰 요청드립니다!
> 
> 우선 syslog, nginx의 access와 error log 는 각각 /var/log/ 와 /var/log/nginx/ 에 있습니다.
> admin 에서 ssh reverse-proxy 접근해서 확인 가능합니다!
> admin 은 13.209.73.178 이고, 접근 전체 열어두었습니다.
> 아.. key 는 이전 미션에서 올려두었는데 필요하시면 말씀해주세요!
> 
> 그리고 aws cloudwatch 에서 애플리케이션의 로그도 연결 했습니다. 이름을 설정 안해서 그랬는지 ip로만 host 에 쌓이고 있었습니다. 기존에 서버-1 만 쌓도록 했었는데, 서버-2, 리버스프록시서버 까지 추가했습니다. 제대로 연결한건지 확인 부탁드립니다!
> 
> 로그를 남기는 위치나 로그 레벨에 대해서 다시 수정을 해보았습니다.
> 
>     * 운영 시의 로그는 처음에 ERROR 로 하려다가, 그러면 aop로 찍으려던 코드상에서 로그를 error로 해야 찍혀서 리뷰 시 확인이 가능할 것 같아서, 로그를 info 로 하고 properties 도 INFO 로 맞춰두었었습니다. 현재 코드의 로그는 info, 운영 시 로그 properties 는 ERROR 로 수정했습니다.
> 
>     * annotationInFileLogging 위에 중복된다고 하셨던 내용에 대한 제 답글은 잊어주세요.. 제가 착각을 했네요. 저 메서드는 중복이 맞습니다. 저건 제가 각 페이지들 이동 시에 로그를 찍을 방법이 있나 해서 In 으로 페이지 호출 url을 찍을 수 있나 테스트 했다가 남겨두었었네요..ㅠㅠ 지웠습니다!
> 
>     * 필요한 메서드만 어노테이션으로 최소의 범위로 로그를 남기도록 했고, 불필요한 메서드들 삭제했습니다.
> 
> 
> 재리뷰 요청드립니다. 감사합니다!!!

형진님 수정하신 내용 확인했습니다.
좀 더 개선해보면 좋을 부분이 있습니다.

1. syslog, nginx의 access와 error log도 aws cloudwatch logs에서 확인 가능하도록 수정해주세요.
각 서버에 직접 접속해서 로그를 확인하는 것보다 한 곳에서 확인하는게 로그 관리하기 더 좋지 않을까요?

2. aws cloudwatch 에서 애플리케이션의 로그 연결하셨다고 써주셨는데 로그 그룹명이 어떤걸까요?
기존에 사용하셨던 로그 그룹명은 itdar라서 들어가보니 최근 로그는 안쌓이고 있네요.

2021-06-30 04:51 UTC, kang-hyungu commented
그리고 log 디렉터리에 file, json 로그로 구분한 이유가 있을까요? json 로그 파일은 json 포멧으로 남기는 걸 의도하신 것 같은데 어디서 확인 할 수 있을까요?

추가로 local에서는 ide의 콘솔에서 로그 확인하도록 만들어야 하지 않을까요?
매번 로그 파일을 조회하면서 개발하면 불편할테니 local은 콘솔에 로그가 남도록 수정해보아요

2021-06-30 04:51 UTC, kang-hyungu requested changes
형진님 피드백 반영하신 내용 확인했습니다.
추가로 점검해보면 좋을 부분에 코멘트 남겼어요
확인해보시고 리뷰 재요청주세요~!

2021-06-30 07:03 UTC, itdar commented
> 그리고 log 디렉터리에 file, json 로그로 구분한 이유가 있을까요? json 로그 파일은 json 포멧으로 남기는 걸 의도하신 것 같은데 어디서 확인 할 수 있을까요?
> 
> 추가로 local에서는 ide의 콘솔에서 로그 확인하도록 만들어야 하지 않을까요?
> 매번 로그 파일을 조회하면서 개발하면 불편할테니 local은 콘솔에 로그가 남도록 수정해보아요

 안녕하세요 현구님. 꼼꼼한 리뷰 감사드립니다!!
분명 제대로 한 것 같았는데 빠진게 많네요..ㅠㅠ

 우선 aws cloudwatch 에서
- (그룹명 itdar-nginx): nginx 와 sys 관련 로그 (itdar-reverse-proxy-nginx)
- (그룹명 itdar): was application 의 file 과 json 로그 (itdar-was-1_2) 
 둘 다 이번에는 여러번 확인했습니다!

- log 디렉터리에 file, json 로그 구분을 한 것은, json은 경로 검색 시에 response 되는 stations 가 많을 수 있어서 더 보기 좋지 않을까 해서 구분해서 만들었습니다! 어떻게 생각하시나요?
- local 에서 ide 콘솔 로그 확인은 properties 에서 기존에 !prod 일 경우에 DEBUG 범위까지 찍히게 해두었었고, 이번에 INFO 범위로 수정했습니다!

인프라가 재미있기도 하면서 어렵네요..ㅎㅎ
재리뷰 요청드리겠습니다. 감사합니다!!

2021-07-01 01:39 UTC, kang-hyungu commented
> > 그리고 log 디렉터리에 file, json 로그로 구분한 이유가 있을까요? json 로그 파일은 json 포멧으로 남기는 걸 의도하신 것 같은데 어디서 확인 할 수 있을까요?
> > 추가로 local에서는 ide의 콘솔에서 로그 확인하도록 만들어야 하지 않을까요?
> > 매번 로그 파일을 조회하면서 개발하면 불편할테니 local은 콘솔에 로그가 남도록 수정해보아요
> 
> 안녕하세요 현구님. 꼼꼼한 리뷰 감사드립니다!!
> 분명 제대로 한 것 같았는데 빠진게 많네요..ㅠㅠ
> 
> 우선 aws cloudwatch 에서
> 
>     * (그룹명 itdar-nginx): nginx 와 sys 관련 로그 (itdar-reverse-proxy-nginx)
> 
>     * (그룹명 itdar): was application 의 file 과 json 로그 (itdar-was-1_2)
>       둘 다 이번에는 여러번 확인했습니다!
> 
>     * log 디렉터리에 file, json 로그 구분을 한 것은, json은 경로 검색 시에 response 되는 stations 가 많을 수 있어서 더 보기 좋지 않을까 해서 구분해서 만들었습니다! 어떻게 생각하시나요?
> 
>     * local 에서 ide 콘솔 로그 확인은 properties 에서 기존에 !prod 일 경우에 DEBUG 범위까지 찍히게 해두었었고, 이번에 INFO 범위로 수정했습니다!
> 
> 
> 인프라가 재미있기도 하면서 어렵네요..ㅎㅎ
> 재리뷰 요청드리겠습니다. 감사합니다!!


로컬일 경우 파일로 저장하는게 아니라 콘솔창에 로그가 보여야 개발이 수월하지 않을까요?
`<appender-ref ref="file" />`에서 file 부분 수정이 필요해보이네요

<img width="639" alt="image" src="https://user-images.githubusercontent.com/15669435/124051991-80558e80-da58-11eb-8ce4-05a260dda5aa.png">

2021-07-01 01:48 UTC, kang-hyungu approved these changes
형진님 cloudwatch logs에 로그 잘 남고 있네요 👍 
추가 코멘트는 다음 미션 진행할 때 참고하세요
pr 머지 처리하겠습니다. 수고하셨어요

2021-07-01 01:48 UTC, merged