Step3 : 로깅, 모니터링
next-step/infra-subway-monitoring pull request #384
Opened 2022-06-24 08:32 UTC by mond-page

안녕하세요, 리뷰어님 ( _ _)
로깅, 모니터링 구성해보았습니다.
개인적으로 쉽지 않은 구성이였네요😭😭 (디스크 용량도 꽉차고, git clone도 안되고 이것저것 난항을 겪었습니다ㅠ)

마지막 리뷰까지 잘 부탁드리겠습니다 🙇‍♂️🙇‍♂️🙇‍♂️

2022-06-25 08:34 UTC, jaeyeonling requested changes
미션을 잘 진행해주셨습니다 👍 
코멘트 남두었으니 확인 부탁드릴게요 😄

2022-06-25 14:16 UTC, mond-page commented on src/main/java/nextstep/subway/auth/application/AuthService.java
>      private MemberRepository memberRepository;
리뷰어님 말씀대로 가독성 면에서 더 좋은 것 같습니다!!

2022-06-25 14:17 UTC, mond-page commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +        fileLogger.info("로그인 시도한 email : {}", request.getEmail());
Aspect 적용해서 `JsonLogAspect`, `FileLogAspect` 두 개로 공통 로깅으로 추출해보았습니다~

2022-06-26 10:13 UTC, jaeyeonling requested changes
코멘트를 잘 반영해주셨습니다 👍 
추가적인 코멘트 남두었으니 확인 부탁드릴게요~

2022-06-26 10:13 UTC, jaeyeonling commented on src/main/java/nextstep/subway/aop/FileLogAspect.java
> +            + "execution(* nextstep.subway.auth.application.AuthService.login(..))")
지금처럼 메서드 단위로 포인트컷을 걸면 로깅이 추가될 때 마다 해당 코드를 수정해야 할 문제가 있을 것 같아요!
해당 코드 수정 없이 로깅을 추가할 수 있도록 해보면 어떨까요?

2022-06-26 10:13 UTC, jaeyeonling commented on src/main/java/nextstep/subway/aop/JsonLogAspect.java
> +        logger.info("find : {} to {}", sourceStation, targetStation);
로깅을 공통으로 처리하는 것이 목적이라면 지금과 같은 코드는 공통으로 사용할 수 없어서 문제가 있을 것 같아요.
공통 이외에 처리하고 싶다면 service에 별도로 추가하는게 좋을 것 같습니다!

2022-06-26 11:01 UTC, mond-page commented on src/main/java/nextstep/subway/aop/FileLogAspect.java
> +            + "execution(* nextstep.subway.auth.application.AuthService.login(..))")
말씀해주신대로 `@PointCut`으로 하면 계속 유지보수면에서 자주 변경해줘야 하는 감이 있네요 😱
해당 부분 `FileLog` Annotation으로 생성자 부분이랑 메소드 부분에서 처리 할 수 있도록 개선하였습니다 : )

2022-06-26 11:02 UTC, mond-page commented on src/main/java/nextstep/subway/aop/JsonLogAspect.java
> +        logger.info("find : {} to {}", sourceStation, targetStation);
Aspect로 뽑았지만, 공통이지 않았네요 ㅠ 
이 부분은 다시 MapService로 넣어서 처리하였고, JsonLogAspect는 제거하였습니다 !

2022-06-27 10:19 UTC, jaeyeonling approved these changes
코멘트를 잘 반영해주셨네요 👍 
미션 진행하시느라 고생 많으셨습니다!
얼마 남지 않았는데 힘내주시고 좋은 소식으로 다시 뵙겠습니다 😄

2022-06-27 10:19 UTC, merged