Step3 - 로깅, 모니터링
next-step/infra-subway-monitoring pull request #400
Opened 2022-06-26 16:45 UTC by kmmin78

안녕하세요, 태엽님! 🙂

6주차 - 서비스 진단하기 Step3 - 로깅, 모니터링 PR 드립니다.

어플리케이션 및 서버 로그 설정, AWS CloudWatch Dashboard 설정까지 무리없이 진행했는데,

저만 그런건지 모르겠지만, 이 프로젝트의 어플리케이션 코드에 오류가 발생해 회원가입과 경로탐색 로그는 못찍고 있네요 🥲

마지막 리뷰도 잘 부탁드립니다! 🙏

2022-06-27 16:22 UTC, enemfk777 commented
> 저만 그런건지 모르겠지만, 이 프로젝트의 어플리케이션 코드에 오류가 발생해 회원가입과 경로탐색 로그는 못찍고 있네요 🥲

어떤 오류가 발생하는지 경로, 조건, 환경, 오류 로그를 자세히 적어주시면 도움을 드릴 수 있을 것 같습니다 :)
일단 민성님 step3 브랜치를 로컬에서 실행시켜봤을 때는 의도하신대로 로그가 잘 남는 것 같아서요 :)

2022-06-27 16:23 UTC, enemfk777 reviewed
안녕하세요 민성님 :)

3단계 잘 수행해주셨습니다.
다만 클라우드워치 대시보드에 위젯이 확인되지 않아 request change 드렸으니,
확인 후 다시 한 번 요청 부탁드립니다!!

2022-06-27 16:23 UTC, enemfk777 commented on README.md
> +- https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=kmmin78-dashboard
현재 대시보드 상에 아무 위젯도 확인되지 않네요 :)

https://edu.nextstep.camp/s/X02BsEA0/ls/2KOKzBnR
힌트를 참고하셔서 위젯 추가 부탁드립니다!

2022-06-27 16:25 UTC, enemfk777 requested changes
안녕하세요 민성님 :)

3단계 잘 수행해주셨습니다.
다만 클라우드워치 대시보드에 위젯이 확인되지 않아 request change 드렸으니,
확인 후 다시 한 번 요청 부탁드립니다!!

2022-06-27 17:31 UTC, kmmin78 commented
제가 위젯을 생성하고 대시보드를 저장하지 않았었군요. 🥲
위젯 생성해두었습니다!

2022-06-27 17:44 UTC, kmmin78 commented
기존에 제대로 동작하지 않던 ```brainbackdoor/data-subway:0.0.3``` 이미지를 제거하고

```docker run -d -p 3306:3306 brainbackdoor/data-subway:0.0.2``` 를 통해 0.0.2 이미지를 재구동한 결과

정상적으로 동작하는 것을 확인했습니다! 😁

2022-06-28 15:03 UTC, enemfk777 approved these changes
안녕하세요 민성님 :)

클라우드워치 위젯 설정도 잘 해주셨고,
어려움을 겪으셨던 부분도 스스로 답을 찾아 주셨네요 💯

이번 미션은 여기서 마치도록 하겠습니다..!!
고생 많으셨습니다 !!
남은 미션과 기간이 얼마 남지 않았는데 무사히 완주하시길 응원하겠습니다 💪

2022-06-28 15:03 UTC, merged