2단계 - 부하테스트
next-step/infra-subway-monitoring pull request #401
Opened 2022-06-26 19:47 UTC by las139

안녕하세요 😃

[2단계 - 부하테스트] 미션에 대한 리뷰 요청드립니다.

지난 1단계 미션 피드백 반영하였습니다.

부족한 부분에 대해서 많은 피드백 부탁드립니다 🙏

2022-06-26 23:23 UTC, ohtaeg requested changes
2단계 미션도 잘해주셨어요 👍 👍 
새벽 5시에 PR을 주시다니.. 대단하신 것 같아요 🔥 
열정적인 모습에 저도 열정적으로 살아보겠습니다 (?)
다음 미션을 진행하기전에 소소한 코멘트를 드렸는데 한번 확인하고
반영될 부분이 있다면 반영하고 진행하면 좋을 것 같아 Request changes 하였습니다..!
확인 후 재요청주시면 감사하겠습니다 🙏

2022-06-26 23:23 UTC, ohtaeg commented on README.md
> +    + (a) 예상 1일 사용자 수(DAU): 10만
DAU 10만은 혹시 어떤 기준으로 산정하신건지 알려주실 수 있으실까요 :) ?
적절한 수치라고 생각하지만, 부하 테스트 미션인만큼 많은 고객을 수용할 수 있는 서비스를 런칭을 목표로
DAU를 증가시켜도 좋을 것 같아서요 😄
꼭 수정해주실 필요는 없는 피드백이오니 한번 고민해보시면 좋을 것 같아요!

2022-06-26 23:23 UTC, ohtaeg commented on README.md
> +      = (6 * 0.1) + 1
T 계산시 요청 수를 6개로 잡아주셨는데요!
스크립트를 확인해보면 `메인 페이지 -> 로그인 -> 경로 검색 -> 즐겨찾기 검색`
총 4개의 요청으로 되어있어서요..! R = 6으로 설정해주신 의도가 있으실까요 :) ?

2022-06-26 23:23 UTC, ohtaeg commented on README.md
> +      = 2s
소숫점 첫째자리 반올림한 수치로군요 😄 
집중률이 조금 낮아서 반올림 해주신 의도일까요 :) ?

2022-06-26 23:23 UTC, ohtaeg commented on k6/script/stress.js
> +    { duration: '4m', target: 0 },
stress 테스트에 맞게 많은 부하를 주셨네요 👍

2022-06-26 23:23 UTC, ohtaeg commented on k6/script/load.js
> +  stages: [
ramp up -> steady state -> ramp down 형태로 잘 구성해주셨어요 👍

2022-06-27 00:14 UTC, las139 commented on README.md
> +    + FCP: pc 2s 이하, 모바일 10s 이하 (현재 pc 2.7s, 모바일 15s 소요)
타경쟁사대비 조금여유롭게 했는데 좀더 짜른속도를 목표로 수정하겠습니다!

2022-06-27 00:15 UTC, las139 commented on README.md
> +      = (6 * 0.1) + 1
앗 처음에 6개였다가 4개로 수정했는데
이부분은 미처 수정하지 못했네요

2022-06-27 03:24 UTC, las139 commented on README.md
> +    + (a) 예상 1일 사용자 수(DAU): 10만
경쟁사 대비 약 절반 정도로 기준을 잡았는데 더 많이 잡아도 될것 같네요

2022-06-27 03:25 UTC, las139 commented on README.md
> +      = 2s
네 맞습니다..
현재는 요청수 4로 바꾸고
결과값도 소숫점나온그대로 사용했습니다

2022-06-27 11:17 UTC, ohtaeg approved these changes
피드백 반영을 잘해주셨어요 👍 👍 
마지막 미션을 남겨두고 계시네요 :)
마지막 미션도 화이팅입니다 🔥

2022-06-27 11:17 UTC, ohtaeg commented on README.md
> +    + FCP: pc 0.8s 이하, 모바일 10s 이하 (현재 pc 2.7s, 모바일 15s 소요)
👍

2022-06-27 11:17 UTC, ohtaeg commented on README.md
> +                   = 2,000,000
피드백 반영 👍

2022-06-27 11:17 UTC, ohtaeg commented on README.md
> +    + 최대 VUser = (92.4 * 1.4) / 6 = 21.56
👍 👍

2022-06-27 11:22 UTC, merged