Step2 - 부하테스트
next-step/infra-subway-monitoring pull request #409
Opened 2022-06-28 14:52 UTC by jaesungahn91

인프라미션을 진행하면서 부족한부분이 너무 많다는걸 다시 깨닫습니다 ㅠㅠ..
많은 피드백 부탁드립니다.

2022-06-29 12:05 UTC, seokhongkim requested changes
재성님, 2단계 미션 잘 진행해주셨습니다. 👍 
미션을 진행하시며 어떤 부분이 궁금하거나 어렵게 느껴지셨는지 궁금하고, 이에 대해 같이 이야기 나눠봐도 좋겠다는 생각이 듭니다. :)

테스트 관련하여 코멘트를 조금 남겼으니 확인 부탁드립니다. 🙏

2022-06-29 12:05 UTC, seokhongkim commented on docs/script/load.js
> +    let loginRes = http.get(`${BASE_URL}/paths?source=113&target=100`);
매번 같은 역을 이용하여 테스트를 진행하면 테스트에 어떤 오류가 발생할 수 있을까요?

2022-06-29 12:05 UTC, seokhongkim commented on docs/script/load.js
> +        { duration: '4m', target: 40 },
피크타임 때 최대 동시 사용자가 40명 정도로 가정하신 걸까요?

2022-06-29 12:05 UTC, seokhongkim commented on docs/script/stress.js
> +    stages: [
ramping up 단계와 유지하는 단계를 모두 설정해주신 점 좋습니다. 👍 
target 을 정한 기준이 있는지 궁금합니다.
그리고 어느 시점부터 에러가 발생했는지, 에러가 발생한 상황이 장기간 유지되는 경우 어떻게 되는지, 일정 시간이 경과하고 vusers 를 낮췄을 때 시스템이 정상적으로 동작하는지도 검증이 됐는지 궁금합니다.

2022-07-01 15:06 UTC, jaesungahn91 commented on docs/script/stress.js
> +    stages: [
target을 max vuser 배수들로 변경했습니다.
vuser 4배정도 됐을때 에러가 발생했고 차단시간이 길어졌으며 vuser를 낮췄을 때 정상수치로 돌아왔습니다.

2022-07-01 15:07 UTC, jaesungahn91 commented on docs/script/load.js
> +    let loginRes = http.get(`${BASE_URL}/paths?source=113&target=100`);
인자를 받아 호출하는 형식으로 변경하긴했는데, 매번 호출시 다른 역을 사용해야하나요?
잘몰라서 여쭤봅니다 ㅠㅠ

2022-07-01 15:07 UTC, jaesungahn91 commented on docs/script/load.js
> +export default function ()  {
이부분은 어떤 방향으로 수정하는게 좋을까요?!

2022-07-02 04:34 UTC, seokhongkim commented on docs/script/load.js
> +export default function ()  {
재성님께서 부하 테스트를 진행하신 목적에 따라 테스트 대상을 정해볼 수 있을 것 같아요!

저는 아래와 같은 기준으로 테스트 대상 API 를 정했습니다.
* 호출이 많이 발생하는 API
* 비즈니스상 중요한 API
* 대량의 데이터를 조회하거나 성능 저하가 발생할 수 있는 API - TPS 측정을 통해 트래픽이 늘어날 때 스케일아웃 필요량 계산

이후, 성능 확인을 원하는 API 단위로 나눠서 테스트를 진행했습니다.
이를 통해 성능 저하 또는 시스템에 부하를 많이 주는 API를 확인할 수 있고, 스케일아웃을 얼마나 해야할지, 어떤 API의 성능을 개선해야 할 지 파악할 수 있었습니다.

2022-07-02 04:37 UTC, seokhongkim commented on docs/script/load.js
> +    let loginRes = http.get(`${BASE_URL}/paths?source=113&target=100`);
동일한 데이터로 조회하는 경우 캐시 서버, DB 캐시 등의 영향으로 실제 사용자가 사용하는 환경과 다른 부분이 발생할 수 있습니다.
성능 테스트의 목적은 사용자가 사용할 때 어느정도의 부하를 버틸 수 있는지 알기 위한 목적이 있으므로, 사용자가 호출하는 것과 유사한 형태의 호출을 만드는 게 좋다고 생각합니다.
실제 사용자의 호출 데이터와 유사하게 만드는 것이 어렵다면 임의의 값을 전달하는 것도 좋은 방법이 될 것 같습니다.

2022-07-02 04:38 UTC, seokhongkim approved these changes
재성님, 2단계 미션 잘 마무리해주셨습니다. 👍 
추가로 코멘트 남긴 내용을 포함해서 학습의 목표는 달성하셨다고 생각되어, PR은 이만 머지하도록 하겠습니다.

3단계 미션에서 뵙겠습니다. 😀

2022-07-02 04:38 UTC, merged

2022-07-02 13:14 UTC, jaesungahn91 commented on docs/script/load.js
> +export default function ()  {
정말 감사합니다!

2022-07-02 13:23 UTC, jaesungahn91 commented on docs/script/load.js
> +    let loginRes = http.get(`${BASE_URL}/paths?source=113&target=100`);
정말 좋은 피드백 감사합니다!!!