step1 리뷰 부탁드립니다.
next-step/infra-subway-monitoring pull request #41
Opened 2021-06-28 13:28 UTC by jis1218

리뷰어님 안녕하세요~ 정인섭이라고 합니다.

이번 미션 잘 부탁드립니다.

처음 경험해보는 것들이 많아 부족한 점이 많을겁니다.

꼼꼼한 리뷰 부탁드릴게요^^

감사합니다!

2021-06-29 03:07 UTC, kang-hyungu requested changes
안녕하세요 인섭님, 만나서 반갑습니다. 리뷰어 강현구입니다 👋 
몇 가지 코멘트 남겼습니다.
확인해보시고 수정하셔서 리뷰 재요청주세요
궁금한 점은 dm 주시거나 코멘트 남겨주세요

2021-06-29 03:07 UTC, kang-hyungu commented on src/main/java/nextstep/subway/auth/domain/LoginMember.java
> +                ", age=" + age +
개인정보를 로그로 남기면 안됩니다.

2021-06-29 03:07 UTC, kang-hyungu commented on src/main/java/nextstep/subway/auth/dto/TokenRequest.java
> +                ", password='" + password + '\'' +
비밀번호는 로그로 남기면 안됩니다.

2021-06-29 03:07 UTC, kang-hyungu commented on src/main/java/nextstep/subway/auth/ui/AuthController.java
> +    private static final Logger log = LoggerFactory.getLogger("console");
```suggestion
    private static final Logger log = LoggerFactory.getLogger(AuthController.class);
```

2021-06-29 03:07 UTC, kang-hyungu commented on src/main/java/nextstep/subway/auth/dto/TokenRequest.java
> +                ", password='" + password + '\'' +
다른 dto도 개인정보를 로그로 남기고 있는지 점검해보아요

2021-06-29 03:07 UTC, kang-hyungu commented on src/main/java/nextstep/subway/favorite/ui/FavoriteController.java
> +    private static final Logger log = LoggerFactory.getLogger("console");
logger 객체가 컨트롤러에서 안쓰이고 있는데... 필요할까요?

2021-06-29 03:07 UTC, kang-hyungu commented on src/main/resources/logback.xml
> +    <include resource="json-appender.xml" />
resources에 json-appender.xml이 없는 것 같은데 확인 부탁드려요

2021-06-29 08:30 UTC, jis1218 commented on src/main/resources/logback.xml
> +    <include resource="json-appender.xml" />
json-appender.xml을 추가하고 logback.xml에서 설정하면 에러가 나더라구요~ qna에는 한번 물어보도록 하겠습니다~

2021-06-29 08:47 UTC, jis1218 commented on src/main/resources/logback.xml
> +    <include resource="json-appender.xml" />
해결해서 올렸습니다!

2021-06-30 05:25 UTC, kang-hyungu requested changes
인섭님 추가 피드백 남겼습니다.
확인해보시고 적용 부탁드려요~!

2021-06-30 05:25 UTC, kang-hyungu commented on README.md
> +  - https://ap-northeast-2.console.aws.amazon.com/systems-manager/resource-groups/cloudwatch?region=ap-northeast-2&dashboard=DASHBOARD-jis1218
aws cloudwatch logs에서 애플리케이션과 nginx 로그를 조회하려는데 로그 그룹명을 어떤 걸로 조회하면 될까요?

2021-06-30 05:25 UTC, kang-hyungu commented on src/main/java/nextstep/subway/log/LogAdvice.java
> +    @Pointcut("execution(* nextstep.subway.*.ui.*Controller.*(..))")
모든 컨트롤러의 실행 이력을 확인하는 용도로 추가하신 것 같네요
실무에서 적용하실 때 패키지명 변경 이슈, 클래스명이 Controller로 고정되는 이슈, 모든 컨트롤러의 이력을 남겨도 이슈가 없을지 고민해보면 좋을 것 같습니다.
미션에서는 연습용으로 추가하신 것으로 보이니 수정은 따로 안하셔도 됩니다.

2021-06-30 16:09 UTC, jis1218 commented on src/main/java/nextstep/subway/log/LogAdvice.java
> +    @Pointcut("execution(* nextstep.subway.*.ui.*Controller.*(..))")
주신 조언 참고하겠습니다! 꼼꼼히 봐주셔서 감사합니다~

2021-07-01 04:49 UTC, jis1218 commented on README.md
> +  - https://ap-northeast-2.console.aws.amazon.com/systems-manager/resource-groups/cloudwatch?region=ap-northeast-2&dashboard=DASHBOARD-jis1218
앱로그 - jis1218-app-log 
nginx access 로그 - jis1218-nginx-access
nginx error 로그 - jis1218-nginx-error

입니다!

2021-07-04 05:35 UTC, kang-hyungu approved these changes
인섭님 피드백 반영 잘하셨습니다.
pr은 머지하겠습니다. 수고하셨습니다!

2021-07-04 05:35 UTC, merged