3단계 - 로깅, 모니터링
next-step/infra-subway-monitoring pull request #426
Opened 2022-07-01 11:14 UTC by Ttungga

안녕하세요 재연님.

3단계 미션 PR 생성하였습니다. 리뷰 부탁드립니다. 🙏 

감사합니다.

2022-07-01 23:21 UTC, jaeyeonling requested changes
미션을 잘 진행해주셨습니다 👍 
코멘트 남겨두었으니 확인 부탁드려요!

2022-07-01 23:21 UTC, jaeyeonling commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +        logger.info("로그인: [ID]-{}", member.getId());
지금의 구조는 로깅을 매 서비스에 추가해줘야 하는데 공통으로 처리해보면 어떨까요?

2022-07-01 23:21 UTC, jaeyeonling commented on src/main/resources/application.properties
> +management.metrics.export.cloudwatch.namespace=ttungga
https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=ttungga-dashboard;start=PT72H

로깅 👍

2022-07-01 23:21 UTC, jaeyeonling commented on src/main/resources/logback.xml
> +<configuration debug="false">
이미 아시겠지만 스프링은 `logback-spring` 혹은 config를 통한 로깅도 지원합니다 ㅎㅎ

2022-07-02 06:28 UTC, Ttungga commented
안녕하세요 재연님~

피드백 감사드립니다.
공통 logger를 사용할 수 있도록 수정 후 커밋 추가하였는데요.
다시 한번 리뷰 부탁드립니다. 🙏 

감사합니다.

2022-07-02 16:29 UTC, jaeyeonling requested changes
코멘트 반영해주신 내용 확인하였습니다~
의미가 잘못 전달된 코멘트가 있는 것 같아 추가 설명 남겨두었으니 확인 부탁드릴게요 😄

2022-07-02 16:29 UTC, jaeyeonling commented on src/main/java/nextstep/subway/common/LoggerProvider.java
> +public class LoggerProvider {
공통처리에 대해 의미가 잘못 전달된 부분이 있는 것 같은데요!
개발자가 매번 로깅을 신경쓰지 않도록 관심사 분리를 해보면 좋을 것 같아 남긴 코멘트였습니다 ㅎㅎ 
관련 키워드로는 `AOP를 활용한 로깅` 등으로 검색해보시면 좋을 것 같아요~

2022-07-03 08:20 UTC, Ttungga commented
안녕하세요 재연님.

제가 이해를 잘못했었군요.
AOP를 통해 로깅 설정 추가하였습니다.
AOP는 서비스 보다는 컨트롤러쪽이 더 적합하다고 생각하여 적용해보았습니다.
리뷰 부탁드립니다. 🙏 

감사합니다.

2022-07-04 03:18 UTC, jaeyeonling requested changes
코멘트를 잘 반영해주셨습니다 👍 
추가적인 내용 남겨두었으니 확인 부탁드려요~

2022-07-04 03:18 UTC, jaeyeonling commented on src/main/java/nextstep/subway/common/AopLogger.java
> +public class AopLogger {
서버에서 많은 트래픽을 받을 경우 지금과 같이 log를 나눠서 남기게 된다면 어떻게 구분해서 확인할 수 있을까요?
또한 로깅을 남겨주신 만큼 toString을 재정의하여 의미있는 로그를 남겨보면 좋겠습니다~

추가로 Controller에 로그를 추가하는게 좋다고 판단하신 이유가 있을까요?

2022-07-04 06:00 UTC, Ttungga commented on src/main/java/nextstep/subway/common/AopLogger.java
> +public class AopLogger {
서비스 단에서 특별히 살펴봐야할 포인트가 있다면 이는 AOP로 처리할 것이 아니라
해당 클래스 내에 직접 로거를 넣어서 설정을 해야한다고 판단했습니다.

AOP를 통해 로깅을 할 것이라면 그 대상은 
애플리케이션에 들어오고 나가는 요청과 응답에 대한 정보를 로깅하는 것이 맞다고 생각합니다.

2022-07-04 06:03 UTC, Ttungga commented
안녕하세요 재연님.

요청/응답에 사용되는 DTO에 toString() 메서드를 추가하였고,
어떤 로그인지 구분할 수 있도록 로그 내용을 수정하였습니다.

리뷰 부탁드립니다.

2022-07-05 01:43 UTC, jaeyeonling requested changes
코멘트를 잘 반영해주셨습니다 👍 
소소한 코멘트 남겨두었으니 확인해주시면 바로 머지하도록 하겠습니다 😄

2022-07-05 01:43 UTC, jaeyeonling commented on src/main/java/nextstep/subway/member/dto/MemberRequest.java
> +                ", password='" + password + '\'' +
password는 민감정보인데 그래도 노출해도 괜찮을까요?

2022-07-05 01:43 UTC, jaeyeonling commented on src/main/java/nextstep/subway/common/AopLogger.java
> +public class AopLogger {
특별히 살펴봐야할 포인트는 별도의 로깅을 해주는 것이 맞지만 공통된 로깅의 경우 Service도 남기는 경우도 많습니다 ㅎㅎ 
일반적으로 Controller에 대한 로깅은 Http 데이터의 로깅을 많이 하는 편이고요~
민철님이 생각하시는 목적에 맞게 로깅해주시면 될 것 같습니다 😄

2022-07-05 16:07 UTC, jaeyeonling approved these changes
코멘트를 잘 반영해주셨습니다 👍 
해당 요청은 머지하도록 할게요~ 
마지막까지 화이팅 해주시고, 좋은 소식으로 다시 뵙겠습니다 😄

2022-07-05 16:07 UTC, merged