3단계 - 로깅, 모니터링
next-step/infra-subway-monitoring pull request #456
Opened 2022-07-06 01:42 UTC by Woody-log

안녕하세요. 재석님 

3단계 미션 작성하여 PR 드립니다.

리뷰 잘 부탁드립니다 🙏🏻

2022-07-06 23:11 UTC, seok-2-o requested changes
로깅, 모니터링 미션 잘 진행해주셨네요.
소소한 고민거리 남겨드렸습니다.
확인 부탁드릴게요.

2022-07-06 23:11 UTC, seok-2-o commented on src/main/java/nextstep/subway/auth/ui/AuthController.java
> +        fileLogger.debug("[로그인 요청] 성공 : {}", token.getAccessToken());
토큰을 로그로 남기는 이유가 있나요?
(1) 토큰을 통해 유저를 알아보기 힘들고 (2) 혹시라도 3자에게 로그가 탈취된다면 어떻게 될까요?

2022-07-06 23:11 UTC, seok-2-o commented on src/main/java/nextstep/subway/auth/ui/AuthController.java
> +        fileLogger.debug("[로그인 요청] 성공 : {}", token.getAccessToken());
로그 레벨을 debug 로 설정하신 이유가 있으신가요?

2022-07-06 23:11 UTC, seok-2-o commented on src/main/resources/file-appender.xml
> +                <maxFileSize>15MB</maxFileSize>
로그 파일의 사이즈를 잘 정해주셨지만, 로그 생성 전략만 있는 것 같아요 :)

만약 운영 환경이라면 로그 데이터는 기가바이트로 쌓일 수가 있는데요!
즉, 로그가 계속해서 쌓이게 되는 경우에 대한 고려도 해보시면 좋을 것 같아요! 😄

2022-07-07 12:13 UTC, Woody-log commented on src/main/java/nextstep/subway/auth/ui/AuthController.java
> +        fileLogger.debug("[로그인 요청] 성공 : {}", token.getAccessToken());
debug 레벨에서만 확인하면 3자에게 탈취할 위험이 적을거라 생각했습니다!
해당 로그 수정했습니다 😀

2022-07-07 22:41 UTC, seok-2-o approved these changes
피드백반영잘해주셨습니다.
이어서 다음 미션 진행해주세요.

2022-07-07 22:41 UTC, merged