[step2] 2단계 - 성능 테스트 리뷰 부탁드리겠습니다~!!
next-step/infra-subway-monitoring pull request #49
Opened 2021-06-29 12:03 UTC by Lee-Chungsun

안녕하세요 리뷰어님 😀

2단계 성능 테스트 리뷰 부탁드립니다.
client VPC를 새로 만들어서 실제 client의 환경과 동일한 조건에서 테스트를 수행했습니다.
경쟁사 비교는 네이버노선도와 비교를 하고 웹 예산을 측정해보았습니다,,

현업에서 API 서버를 구축하고 운영도 해보고 다양한 경험을 했지만 실제로 서버, 웹 서비스의 성능을 진단해보고
적당한 예산이 어느정도인지를 파악해본 경험이 없기도 하고, 정답도 없다고 생각합니다,,

이번 기회를 통해서 실제로 제가 만든 서비스에 대해 성능을 검증하고 더 효율적으로 개발과 운영을 할 수 있도록
검증할 수 있게 되었으면 좋겠습니다,,

하나하나 세세한 리뷰와 노하우를 부탁드리겠습니다,,.😥😥😥

2021-06-30 10:24 UTC, hhlyn0328 requested changes
성능테스트를 잘 작성해주셨네요 ! 

조금 더 고민해보셨으면 하는 부분이 있어서 
피드백 드렸습니다 :)

2021-06-30 10:24 UTC, hhlyn0328 commented on README.md
> +    > 네이버 지하철 노선과 비교해봤을 때 적당하다고 생각한 수치입니다.
경쟁사와 비교하여 기준을 정한 것 좋습니다 👍 
경쟁사의 대략적인 수치를 함께 작성해주셨으면 좋을 거 같아요 
더 높게 잡았다면 이유는 무엇인지, 낮게 잡았다면 이유는 무엇인지 궁금해요 ㅎㅎ

2021-06-30 10:24 UTC, hhlyn0328 commented on README.md
> +    200 으로 설정했고, 30초 정도 노선을 조회하고 경로 조회하는데에 소모된다 예상했습니다.
300으로 설정하니 실패하여, 200으로 설정했다 ! 는 이 미션의 목적과 맞지 않는 것 같아요 
이 시스템이 견뎌야하는 목표값을 먼저 설정하고, 이에 미치지 못하면 계속해서 개선할 점을 찾아야한다고 생각합니다

아래를 기준으로 DAU 부터 정의해볼까요?
그리고 정해진 목표값에 따라 load test와 stress test의 값을 정해볼 수 있을 거 같아요

```
* 목푯값 설정
우선 예상 1일 사용자 수(DAU)를 정해봅니다.
피크 시간대의 집중률을 예상해봅니다. (최대 트개픽 / 평소 트래픽)
1명당 1일 평균 접속 혹은 요청수를 예상해봅니다.
이를 바탕으로 Throughput을 계산합니다.
Throughput : 1일 평균 rps ~ 1일 최대 rps
1일 사용자 수(DAU) x 1명당 1일 평균 접속 수 = 1일 총 접속 수
1일 총 접속 수 / 86,400 (초/일) = 1일 평균 rps
1일 평균 rps x (최대 트래픽 / 평소 트래픽) = 1일 최대 rps
Latency : 일반적으로 50~100ms이하로 잡는 것이 좋습니다.
사용자가 검색하는 데이터의 양, 갱신하는 데이터의 양 등을 파악해둡니다.
```

2021-06-30 12:31 UTC, Lee-Chungsun commented
제가 문서를 꼼꼼히 읽지 않았군요 ,,ㅠㅠ😢😢
문서를 다시 읽고 부하테스트 조건을 결정해보니 어느정도 감이 온 것 같습니다

2021-07-01 18:08 UTC, hhlyn0328 requested changes
리뷰 반영을 잘 해주셨네요 👍 
같이 고민을 조금만 더 해보면 좋을 거 같아서 
한 번 만 더 수정요청 드릴게요! 😃

2021-07-01 18:08 UTC, hhlyn0328 commented on README.md
> +        { duration: '30s', target: 0 }
rps 22.8 를 확인해보려면 vus 는 몇 이어야 할까요?
https://k6.io/blog/ref-how-to-generate-a-constant-request-rate-in-k6/

2021-07-01 18:08 UTC, hhlyn0328 commented on README.md
> +![img.png](img.png)
stress 테스트를 제외하고는 http_req_failed 가 0%여야 할 거 같아요

2021-07-02 16:55 UTC, Lee-Chungsun commented on README.md
> +![img.png](img.png)
메서드를 잘못 봤네요,, ```/line/{id}/sections``` 는 조회메서드가 아닌데,, 😢
수정하니 0%로 결과가 출력됩니다!

2021-07-02 17:12 UTC, Lee-Chungsun commented on README.md
> +        { duration: '30s', target: 0 }
T = (R * http_req_duration) + 1s  → R : 6개 메서드요청, http_req_duration : 3초
T = (6 * 3) + 1 -> 19초
VU = (Request Rate * T) / R → Request Rate : 22.8, T : 19, R : 3
VU = 144.4

로 나옵니다!

2021-07-04 22:36 UTC, hhlyn0328 commented on README.md
> +        { duration: '30s', target: 0 }
현재 충선님께서 진행하신 로드 테스트는 416 rps 을 확인하고 계시다고 보시면 됩니다 
![스크린샷 2021-07-05 오전 7 23 39](https://user-images.githubusercontent.com/41069113/124401059-1d1e7180-dd62-11eb-8d1e-af24f35b5678.png)

http_req_duration 이 3초여서 VU 계산이 좀 더 크게 된 거 같아요 
스모크 테스트의 평균값을 넣어볼까요?

2021-07-04 22:52 UTC, hhlyn0328 approved these changes
리뷰 사항 반영을 잘 해주셨네요 
많은 고민해주신 것이 느껴집니다 👍 

질문 주신 내용에 대해 답변 남겨두었으니 확인 부탁드려요 ! 
이 과정에서는 성능을 완벽하게 개선하는 것이 아닌, 
성능 테스트를 진행하는데에 목적이 있기때문에 여기에서 마무리하겠습니다! 

과정의 끝까지 무사완주하시길 응원할게요 🔥

2021-07-04 22:52 UTC, hhlyn0328 commented on README.md
> +    http_req_duration: ['p(99)<400'], // 99% of requests must complete below 1.5s
목표는 100ms 이하이므로  'p(99)<100' 으로 변경해볼까요?
그럼 현재 스모크 테스트도 가끔 100ms을 넘어서, 성공하지 못하는 케이스가 생길텐데요

성능을 추가적으로 개선할 수도 있겠지만, 가장 큰 것은 6개의 요청을 하나의 테스트에서 진행하고 있기때문인거 같아요 
정확히 병목인 구간을 찾아내기 위해서 각각 요청에 대한 3가지 테스트를 작성해보면 어떨까요?

2021-07-04 22:52 UTC, hhlyn0328 commented on README.md
> +* stress test
stress test는 성공에 목적이 있는게 아닌, 목표치 이상으로 시스템 자체의 한계를 검증해보는 것이라고 생각하시면 좋을 거 같아요 

```
지금은 내가 경쟁사에 비해 낮게 기준을 잡앗지만 
점점 사용자가 증가 할 때, 아 stress test했을 때, 일 접속자 100만명 증가하는 것 까지는 버틸 수 있었어. 
곧 100만명이 증가하겠군 서버를 미리 증설해야겠어!  
```
등의 계획을 할 수 있는 테스트라고 봐주시면 좋을 거 같습니다 

그래서 수를 점점 늘려가면서 목표치는 넘었지만 100%로 성공하는 경계선도 알아보고 
다양한 정보를 찾아보시면 좋을 거 같아요 ㅎㅎ

2021-07-04 22:52 UTC, merged