Step3 로깅, 모니터링 리뷰 부탁드립니다!
next-step/infra-subway-monitoring pull request #567
Opened 2022-12-06 20:56 UTC by ilmare-cbk

안녕하세요 우테캠 Pro5기 교육생 천보경입니다!
3단계 미션에 대한 리뷰 부탁드립니다!

로그 설정하기
- MemberService와 AuthService에서 대해서  file 로그를 남기도록 처리했습니다.
- MapService에 대해서  json 로그를 남기도로 처리했습니다.
- Nginx Log 설정 시 docker 컨테이너 내 경로를 /home/ubuntu/nextstep/log/nginx로 마운트 되도록 설정했습니다.

cloudwatch로 모니터링
- USE 방법론을 활용하여 E -> U -> S 순으로 컴포넌트들을 볼 수 있도록 대시보드를 구성했습니다.
- E : 에러를 확인하기 위해 access log와 console log를 추가했습니다.
- U : 자원의 사용정도를 확인하기 위해 CPU/MEM/DISK 관련 지표를 추가했습니다.
- S : 부하정도를 확인하기 위해 Network io와 thread 상태 관련 지표를 추가했습니다.

----
미션 진행하면서 궁금한점 생겨서 질문 남깁니다 😃
질문) 현재 애플리케이션 ec2 서버가 2대라서 각각 서버에 로그 관련 처리를 했습니다. 서버가 많아지는 경우 매번 이렇게 처리하기는 어려울 것 같은데 실무에서 일괄적으로 처리하는 방식?들이 있을까요?

2022-12-07 16:37 UTC, chae-yh requested changes
보경님 안녕하세요. step2에 대한 피드백 반영 및 step3의 환경 구성도 잘해주셨습니다 👍 다만 조금 더 고민해주시면 좋을만한 내용들이 있어 코멘트 드리니 확인 부탁드립니다...! 추가로 질문 주신 내용도 같이 코멘트 드렸습니다 ㅎㅎ

감사합니다 : )

2022-12-07 16:37 UTC, chae-yh commented on README.md
> +ERRO[1691] some thresholds have failed
2단계 피드백 👍

2022-12-07 16:37 UTC, chae-yh commented on README.md
> +<summary>애플리케이션 진단하기 실습을 진행해보고 문제가 되는 코드를 수정</summary>
findAll에서 sleep을 주는 부분 잘 수정 해주셨습니다 👍 그런데 문제가 있는 코드가 더 있는데 한 번 더 확인해주시면 어떨까요...?

2022-12-07 16:37 UTC, chae-yh commented on README.md
> +- https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=ilmare-cbk-dashboard
대시보드 잘 만들어주셨네요 👍 그런데 해당 어플리케이션에 DB는 안 붙어있는 것 같아요..! DB도 붙여보고, 해당 모니터링도 추가해보면 어떨까요...?

2022-12-07 16:37 UTC, chae-yh commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger("file");
file과 json을 혼용해서 로그를 쌓고 있는데, 혹시 구분의 기준은 어떻게 되는 걸까요...?

2022-12-07 16:37 UTC, chae-yh commented on src/main/resources/logback.xml
> +<?xml version="1.0" encoding="UTF-8"?>
logback설정도 잘 해주셨네요 👍 
보통 실무에서는 logback에서 profile에 따른 로그 레벨을 설정해주고는 합니다. local, dev 등 개발 환경의 경우는 log level을 debug까지 보이게 하고, 실제 운영 환경은 info만 보이게 하는 등의 설정을 주로 해줍니다. 이번 미션에서 해당 내용을 직접 반영하실 필요는 없지만, 해당 내용을 고민해보는 것도 좋은 공부가 될 것 같습니다. 참고 부탁드립니다 : )

2022-12-07 16:37 UTC, chae-yh commented on build.gradle
> +	implementation("org.springframework.boot:spring-boot-starter-actuator")
https://ilmare-cbk-subway.kro.kr/actuator 
이런 곳에서 해당 metric 확인도 가능합니다..!

2022-12-07 16:37 UTC, chae-yh commented on src/main/java/nextstep/subway/member/application/MemberService.java
> +        LOGGER.info("Member successfully created : member email = {}", member.getEmail());
사실 로깅은 비지니스 로직과 밀접한 관련이 있지는 않습니다. 이렇게 비지니스 로직 사이사이에 넣지 말고 AOP를 사용해서 관심사 분리를 해보는 것은 어떨까요...?

2022-12-07 16:37 UTC, chae-yh commented on README.md
> +  - console log : /home/ubuntu/nextstep/log.app.log
질문주신 내용은 아무래도 이런 부분과 관련이 깊을 것 같아 여기서 답변드리겠습니다...!

```
미션 진행하면서 궁금한점 생겨서 질문 남깁니다 😃
질문) 현재 애플리케이션 ec2 서버가 2대라서 각각 서버에 로그 관련 처리를 했습니다. 서버가 많아지는 경우 매번 이렇게 처리하기는 어려울 것 같은데 실무에서 일괄적으로 처리하는 방식?들이 있을까요?
```
서버마다 수기로 이런 설정을 하게되면 실수가 발생할 수도 있고, 서버마다 로그의 위치가 달라지는 등 관리가 어려워질 수 있는 포인트가 있습니다. 관련하여 여러가지 방식이 있을테지만, 저희는 배포 시점에 스크립트 등을 통해 서버 내에서 관련 설정들을 자동으로 처리하도록 합니다. application log / tomcat log / nginx log 등 로그에 대한 관리나, application 실행 시 힙메모리 설정 등 인프라 레벨에서 처리해야 하는 것들은 배포 시점에 자동으로 처리할 수 있도록 하여 수기로 작업 시 발생할 수 있는 포인트를 줄이려고 합니다.
특히 최근에는 클라우드 환경에서 서버의 개수가 자유롭게 줄거나 늘어나기 때문에 더더욱 이러한 자동화의 필요성이 클 것 같아요...!
추가로, 작업 중에 궁금한 점에 대해서 잘 질문해주시는 것 같아서 좋네요 👍

2022-12-08 14:29 UTC, ilmare-cbk commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger("file");
따로 구분한 기준은 없고 학습차원에서 두가지 방식을 혼용해서 사용했습니다!
혹시 두 가지 방식이 어느상황에 써야하는지  정해진 룰이 있을까요?🧐

2022-12-09 13:40 UTC, ilmare-cbk commented on README.md
> +  - console log : /home/ubuntu/nextstep/log.app.log
상세한 답변 감사합니다 😄

2022-12-09 14:23 UTC, ilmare-cbk commented
피드백 주신 사항에 대해서 다음과 같이 반영했습니다!
1. 애플리케이션 진단하기 실습을 통한 문제가 되는 코드 수정
->  lock-left, lock-right, tan API를 제거 (실제 비즈니스 기능과 무관하기 때문에 제거)
2. profile에 따른 로깅레벨 설정
-> default, local에 대해서는 debug, prod에 대해서는 info 레벨로 설정했습니다.
3. AOP를 통해 로그를 남기는 관심사를 비즈니스 로직과 분리했습니다.
4. DB에 대한 모니터링을 위해 jdbc connection에 대한 컴포넌트를 대시보드에 추가했습니다.

2022-12-09 19:28 UTC, chae-yh commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger("file");
이 부분은 로그를 다루는 환경에 따라 다를 것 같아요...! 어플리케이션 로그 검색을 쉽게 하기 위해서 환경 구성(ELK, Grafana Loki 등)을 해주는 경우는 데이터 처리를 쉽게하기 위해 json으로 파일을 만드는 경우가 있고, 간단하게 server에서 확인하기 위해 file형태로 쌓는 경우도 있는 것 같습니다.

그리고 이 이모지(🧐) 뭔가 귀엽네요 ㅎㅎㅎㅎㅎ

2022-12-09 20:05 UTC, chae-yh approved these changes
보경님 안녕하세요! 피드백 잘 반영해주셨습니다 💯 질문 주신 내용 및 조금 더 확인해주시면 좋을만한 내용이 정말 살짝있어 코멘트 드렸는데 시간되실 때 확인주시면 좋을 것 같습니다 ㅎㅎ

그리고, 여기까지가 제가 드리는 서비스진단하기 미션의 마지막 피드백인 것 같습니다...! 피드백을 많이 드렸던 것 같은데, 잘 반영해주셔서 감사했습니다. 중간중간 환경 구성 중 질문주셨던 부분에 대해서, 저 스스로도 다시 한 번 고민하게되는 포인트가 있어 도움이 됐던 것 같아요 : )
남은 미션도 지금 진행하셨던 것 처럼 많이 고민하시면서 진행하시면 좋은 결과가 있지 않을까 생각합니다...!

남은 미션도 파이팅하시고, 꼭 완주하시길 바랍니다. 고생 많으셨습니다.
감사합니다 : )

2022-12-09 20:05 UTC, chae-yh commented on README.md
>  2. Cloudwatch 대시보드 URL을 알려주세요
질문주신 내용 여기서 답변드리겠습니다...!

```
jdbc connection에 대한 컴포넌트를 대시보드에 추가를 했습니다.
궁금한 것은 현재 database ec2 서버에 docker 컨테이너를 띄운 상태인데 docker 컨테이너 내부에 생성되는 로그를 cloudwatch에 추가해달라는 말씀이셨을까요?(맞다면 이와 관련된 레퍼런스 문서도 있을까요?? 제가 인프라와 관련된 지식이 약하다보니 말씀해주신 부분들에 대해서 잘 이해가 안가 계속 문의드리게 되네요 ㅎㅎㅎ 😅)
```

문의 드렸던 내용은, 어플리케이션 서버 / 웹 서버와 같이 DB 서버 자체에 대한  CPU 사용량 등의 모니터링을 추가하는 부분이었습니다...! docker로 인프라를 구성했다하더라도 결국 CPU나 메모리, 디스크 사용량과 같은 리소스 사용 등은 서버에 영향을 미치므로 이 부분을 모니터링 하면 좋을 것 같아서 말씀드렸습니다 ㅎㅎ
추가로, 단순히 Server1, 2 정도가 아니라 기능에 따라 분리(application, web 등) 해주어도 좋을 것 같습니다..!

추가로, 계속 질문 주시는 부분은 좋다고 생각들어 언제든 말씀주셔도 좋습니다 : )

2022-12-09 20:05 UTC, chae-yh commented on src/main/java/nextstep/subway/SubwayApplication.java
> +@EnableAspectJAutoProxy
AOP를 위한 어노테이션 추가 👍

2022-12-09 20:05 UTC, chae-yh commented on src/main/java/nextstep/subway/station/domain/Station.java
> +    public String toString() {
아마 로깅 때문에 toString을 Override해주신 것 같네요 👍 
실무에서는 보통 lombok으로 간단하게 처리해주는데, 코드 제네레이터로 하셨겠지만 그래도 역시 어려운 작업인 것 같습니다...! ㅎㅎ

2022-12-09 20:05 UTC, chae-yh commented on src/main/java/nextstep/subway/common/LogAop.java
> +                className, methodName, parameter, result, System.currentTimeMillis() - start);
실행시간 표시해주는 것도 좋네요 👍

2022-12-09 20:05 UTC, chae-yh commented on src/main/java/nextstep/subway/common/LogAop.java
> +public class LogAop {
AOP 구현 👍

2022-12-09 20:08 UTC, merged

2022-12-10 12:33 UTC, ilmare-cbk commented on README.md
>  2. Cloudwatch 대시보드 URL을 알려주세요
네! 늘 상세하게 답변해주셔서 진심으로 감사합니다!