[sixthou] - Step2 PR 리뷰 부탁드립니다.
next-step/infra-subway-monitoring pull request #578
Opened 2022-12-08 08:31 UTC by sixthou

근환님, 안녕하세요~!

step2 리뷰 부탁드립니다.
로그 설정에 따른 디스크 용량 부족과, 테스트 스크립트를 잘 못 작성해서 서버가 죽는등 어려움이 많았네요..😅
이번에도 잘 부탁 드립니다~

2022-12-08 16:56 UTC, geunhwanlee requested changes
부하테스트 잘 해주셨네요 👍🏻

다만 목표로 설정하신 테스트 조건과 실제 테스트가 맞지 않는 부분이 있는것 같아요.

한번 확인해보시고 재 리뷰요청 주세요 🙏

그럼 화이팅하세요 💪

2022-12-08 16:56 UTC, geunhwanlee commented on src/main/resources/docs/load/load-avg.js
> +        http_req_duration: ['p(99)<1500'], // 99% of requests must complete below 1.5s
목표 레이턴시를 100ms로 설정하였으니
100ms 이내로 오는지 확인해봐야겠네요. 😀

2022-12-08 16:56 UTC, geunhwanlee commented on src/main/resources/docs/load/load-avg.js
> +    findPath(accessToken);
시나리오 형태로 잘 작성해주셨네요 👍🏻

2022-12-08 16:56 UTC, geunhwanlee commented on src/main/resources/docs/stress/stress.js
> +    ],
시스템의 한계까지 테스트해보면 좋을것 같네요. 😀
문제가 생기는 시점부터 천천히 트래픽을 줄여가면서 시스템이 복구되는지도 확인해보면 좋을것같아요!

2022-12-09 03:03 UTC, sixthou commented on src/main/resources/docs/load/load-avg.js
> +        http_req_duration: ['p(99)<1500'], // 99% of requests must complete below 1.5s
아이구 이 부분을 놓쳤었네요! 수정해서 다시 테스트 진행했습니다

2022-12-09 03:08 UTC, sixthou commented on src/main/resources/docs/stress/stress.js
> +    ],
아래처럼 수정해서 테스트 진행해보았습니다.
VUser 가 200 명을 넘어가는 시점부터 rps가 증가하지 않고 일정하게 유지되었고, http_req_blocked 가 급격히 증가함을 확인했습니다.
이후 서서히 VUser가 줄면서 정상상태 범위로 들어와서 시스템이 복구되었다고 생각됩니다

```javascript
stages: [
        {duration: '2m', target: 40},
        {duration: '2m', target: 85},
        {duration: '2m', target: 120},
        {duration: '2m', target: 160},
        {duration: '2m', target: 200},
        {duration: '2m', target: 250},
        {duration: '2m', target: 300},
        {duration: '2m', target: 350},
        {duration: '2m', target: 250},
        {duration: '2m', target: 200},
        {duration: '2m', target: 160},
        {duration: '2m', target: 120},
        {duration: '2m', target: 85},
        {duration: '2m', target: 40},
        {duration: '2m', target: 0},
    ],
```

2022-12-09 17:52 UTC, geunhwanlee approved these changes
리뷰 반영 잘 해주셨어요~

머지하도록 하겠습니다.

그럼 다음단계도 화이팅하세요 🔥

2022-12-09 17:52 UTC, merged