2단계 - 부하 테스트 리뷰 요청
next-step/infra-subway-monitoring pull request #629
Opened 2022-12-13 06:31 UTC by yomni

안녕하세요!
성능 테스트에 대한 학습이 부족하여,
이번에도 학습 후 미션 진행하였습니다.

성능 테스트 라는 것이 참 어려운 점이,
_**논리적인 목표를 설정하기 때문에, 테스트 결과 값을 100% 신뢰할 수는 없다.**_ 라는 점인것같습니다.

여러모로 다른 시스템을 사용하면서 사용자 관점에서 성능이 느리면 불편한 기색을 내비췄던 제가 부끄러워지네요..🫠
(예약 시스템 등을 이용할 때...)

따라서 일반적인 B2C 서비스를 운영할 때, 이런 지표들을 계속해서  
추적 & 관리 해야 될 필요성과어려움을 동시에 느끼는 미션이었습니다!

리뷰 미리 감사드립니다!

오늘부터 날이 추워진다는데 감기 조심하시길 바랍니다🥶

2022-12-14 08:55 UTC, limwoobin commented
그라파나 결과, k6 결과 이미지가 누락된것같은데 같이 첨부 부탁드립니다!

2022-12-14 08:56 UTC, limwoobin requested changes
안녕하세요 용민님
2단계 미션도 잘 해주셨네요 ㅎㅎ

지난번도 이번에도 사전정리를 정말 잘 해주셔서 
저도 리뷰하면서 많이 배우고있습니다
피드백에 대한 회고도 작성해주신것도 굉장히 좋네요 👍 

몇가지 코멘트를 남겨드렸는데 확인해주시고 다시 요청부탁드립니다!

2022-12-14 08:56 UTC, limwoobin commented on README.md
> +
👍👍👍

2022-12-14 08:56 UTC, limwoobin commented on README.md
> +  - 스트레스 테스트 이후 시스템이 수동 개입 없이 복구되는 지 확인
굉장히 잘 정리해주셨네요!
저도 정말 많이 배우게되네요 ㅎㅎ

2022-12-14 08:56 UTC, limwoobin commented on README.md
> +> ![scaling.png](images%2Fstep2%2Fscaling.png)
파일경로가 깨진건지 잘못설정되어있네요ㅠ
이미지는 확인했습니다!

2022-12-14 08:56 UTC, limwoobin commented on README.md
> +- `노선 조회` : 데이터를 조회하는 데 여러 데이터를 참조하는 페이지
타겟시스템범위에 대해 잘 설명해주셧네요 ㅎㅎ
경로검색 페이지 접근도 추가하는것도 괜찮아보입니다!

2022-12-14 08:56 UTC, limwoobin commented on k6scripts/load_path.js
> +}
메인페이지 접근, 경로조회를 따로따로 테스트하신걸까요??
유저플로우를 보면 `메인접근 > 경로조회페이지접근 > 경로조회` 와 같은 흐름으로 진행될것으로 예상되는데
한번에 위 플로우를 모두 테스트하는건 어떨까요??

2022-12-14 08:56 UTC, limwoobin commented on k6scripts/load_main.js
> +    ],
<img width="984" alt="image" src="https://user-images.githubusercontent.com/28802545/207550147-d789c871-4785-4fc4-aa95-a5aedd3088a3.png">
테스트 시간에 대해 한번 고민해보는건 어떠실까요?

2022-12-14 08:56 UTC, limwoobin commented on k6scripts/load_main.js
> +        http_req_duration: ['p(99)<1000'],
<img width="611" alt="image" src="https://user-images.githubusercontent.com/28802545/207550446-685d79ab-a754-4e8e-a232-3c08c6927946.png">

load, smoke 테스트에서 1000은 좀 긴거같기도 하네요!
stress 테스트에서도 살짝 낮춰보아도 괜찮을것같습니다!

2022-12-15 00:14 UTC, yomni commented on k6scripts/load_path.js
> +}
아하 한 스크립트 내에서 플로우를 지정해서 테스트할 수 있는걸 몰랐습니다!
학습 후 모두 테스트해보는것으로 변경해서 진행해보겠습니다!

2022-12-15 00:15 UTC, yomni commented on k6scripts/load_main.js
> +    ],
Load Test의 경우 30분 ~ 2시간 사이로 테스트 시행해보겠습니다!

2022-12-15 00:16 UTC, yomni commented on k6scripts/load_main.js
> +        http_req_duration: ['p(99)<1000'],
smoke는 정상적인 구동 여부를 확인하는 테스트로 이해했습니다.
따라서 1000으로 유지하고,

load, stress는 100이하로 낮춰보겠습니다!

2022-12-15 10:21 UTC, limwoobin commented on k6scripts/load_main.js
> +        http_req_duration: ['p(99)<1000'],
넵 말씀하신 방향 좋습니다 👍

2022-12-15 10:27 UTC, limwoobin commented
그라파나 테스트 결과이미지가 하나만 있는걸로 보여집니다.
smoke, load, stress 세가지 경우에 대해 이미지를 첨부해주시면 좋을것같아요!
다음 미션진행하며 올려주시면 좋겟습니다 ㅎㅎ

2022-12-15 10:28 UTC, limwoobin approved these changes
안녕하세요 용민님
2단계 미션하느라 고생많으셨습니다!

몇가지 코멘트를 남겨드렸으니 다음미션 진행하며
같이 확인해주시면 좋을듯 합니다!
다음 미션도 화이팅입니다!

2022-12-15 10:28 UTC, limwoobin commented on k6scripts/stress.js
> +        http_req_duration: ['p(99)<100'],
stress테스트에 대해서는 duration을 조금 더 길게 가져가셔도 좋지 않을까 싶은데 
어떻게 생각하시나요??
현재 설정하신 duration으로는 지표가 어떨지 궁금하기도 하네요 ㅎㅎ

2022-12-15 10:28 UTC, merged