[yeojiin(임정연)] - 3단계 로깅, 모니터링
next-step/infra-subway-monitoring pull request #655
Opened 2022-12-17 15:52 UTC by yeojiin

안녕하세요 원철님~ 
인프라 미션은 경험이 없는 제겐 하나하나가 어려운 미션이네요🤣
그래도 하나씩 해결해 나가는 재미가 있어요~
특히, 모르는게 많아 찾아가며 미션을 진행하다보니 서버에 대한 이해도가 많이 높아진 것 같습니다!
아직 도커나 aws에 부족한 점이 많지만 최선을 다해 이번 미션을 진행했습니다!
마지막 미션 리뷰도 잘 부탁드립니다!🙏

2022-12-18 02:42 UTC, heowc requested changes
3단계까지 고생 많으셨습니다

대부분의 요구사항을 잘 해결해주셨으나, 누락된 부분이 있는 것 같아 확인차 request changes를 드렸습니다.
고민이 필요한 부분은 반영을 해주셔도 되고 안해주셔도 됩니다 👍 

궁금하신 점이나 이야기 나누고 싶은 부분이 있다면 깃헙 코멘트, 슬랙 DM 편하게 남겨주세요! 
마지막 피드백까지 화이팅입니다 👍

2022-12-18 02:42 UTC, heowc commented on README.md
> +- https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=yeojiin
agent으로 받은 것만 대시보드로 표현되는 것 같은데 그외에 메트릭은 필요없을까요?

jvm 기반의 애플리케이션 특성상 운영시 이것들 이외에도 여러가지 지표를 같이 봐야 보다 유의미할 수 있을 것 같아요 🤔 
- 어떤 것들이 있을까요?
- 또 그 외에 어떤 것들을 보면 좋을까요?

2022-12-18 02:42 UTC, heowc commented on src/main/java/nextstep/subway/auth/dto/TokenRequest.java
> +    public String toString() {
`toString`을 재정의해주셨네요 👍

2022-12-18 02:42 UTC, heowc commented on src/main/java/nextstep/subway/auth/domain/LoginMember.java
> +                ", email='" + email + '\'' +
이메일 같은 경우는 개인정보이기 떄문에 마스킹하는 것이 좋을 것 같아요 👍

2022-12-18 02:42 UTC, heowc commented on src/main/java/nextstep/subway/common/LogAop.java
> +        String parameter = getParameterInfo(pjp, (MethodSignature) signature);
1. 파라미터와 결과를 모드 찍는 것이 적절한지 고민해보면 좋을 것 같아요~
단순한 오브젝트가 전달 받거나 하는건 상관없을 수 있지만
- hibernate/proxy 객체의 의도치 않은 동작
- collection 형태의 데이터들
- 그외 상황들..?
에 대한 고려가 되어야 할 수 있을 것 같습니다 👍 

2. 또한, 지금 같은 형태의 AOP만 사용하게된다면 로그레벨이 하나로 가져갈 수 없게 될 것 같아요 🤔 
3. `json`, `file` 를 사용하는 요구사항이 있는데 해결이 안된 것 같아요~

2022-12-18 02:42 UTC, heowc commented on src/main/java/nextstep/subway/member/application/MemberService.java
> +import org.slf4j.LoggerFactory;
사용되지 않는 import 인것 같습니다 🤔

2022-12-18 02:42 UTC, heowc commented on src/main/java/nextstep/subway/map/application/MapService.java
> +
다시 생각해보면 AOP는 단순하게 하고 상태나 필요한 정보는 각 서비스에서 적절하게 로그 넣는건 어떨까요? 
어떻게 생각하시나요 🤔

2022-12-19 01:25 UTC, yeojiin commented on README.md
> +- https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=yeojiin
로그 그룹, jvm thread status, jdb connection 등을 추가했습니다!
어떤 지표들이 가시적으로 유의미할지 좀 더 고민해보겠습니다~

2022-12-19 01:26 UTC, yeojiin commented on src/main/java/nextstep/subway/map/application/MapService.java
> +
해당 방식이 더 관리하기 용이할 거 같아 수정했습니다~

2022-12-19 01:28 UTC, yeojiin commented on src/main/java/nextstep/subway/common/LogAop.java
> +        String parameter = getParameterInfo(pjp, (MethodSignature) signature);
여러가지가 고려되어야 하네요🤔
파라미터와 결과를 모두 찍는 건 개발 시에만 적용되어도 될 부분 같네요.
너무 많은 정보가 노출되는 거 같기도 하고요!
확인이 필요한 내용으로 범위를 좁혀봤습니다.

- hibernate/proxy 객체의 의도치 않은 동작
- collection 형태의 데이터들
- 그외 상황들..?

위 내용은 제가 좀 더 고민해봐야할 부분인 거 같네요.😂

요구사항에 부합하지 못했던 부분도 다시 올려 확인했습니다~
감사합니다!🙏

2022-12-19 12:48 UTC, heowc approved these changes
마지막 피드백 까지 고생 많으셨습니다 👍 

이번 미션을 통해 조금의 배움(?)이 있으셨길 바래요 🙇 
이제 얼마 남지 않았으니 마지막까지 화이팅입니다

다음 단계를 진행해주세요 💯

2022-12-19 12:48 UTC, heowc commented on src/main/java/nextstep/subway/common/MaskingUtils.java
> +    private static final String MASK_EMAIL_PATTERN = "\\b(\\S+)+@(\\S+.\\S+)";
https://github.com/hibernate/hibernate-validator/blob/main/engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/AbstractEmailValidator.java#L35

이메일에 대한 스펙은 보다 복잡하기 때문에 참고해보시면 좋을 것 같아요 👍

2022-12-19 12:48 UTC, heowc commented on src/main/java/nextstep/subway/common/MaskingUtils.java
> +    private static final String MASK_EMAIL_ID_MORE_PATTERN = "\\b(\\S+)[^@][^@][^@]+@(\\S+)";
Pattern에도 replace에도 있어서 활용하면 좋을 것 같습니다

2022-12-19 12:48 UTC, heowc commented on src/main/java/nextstep/subway/member/domain/Member.java
> +                ", email='" + MaskingUtils.getMaskedEmail(email) + '\'' +
마스킹 처리 👍

2022-12-19 12:48 UTC, heowc commented on src/main/java/nextstep/subway/map/application/PathService.java
> +        jsonLogger.info("Find Path - Start '{}', End '{}'", source, target);
json logger 활용 👍

2022-12-19 12:48 UTC, merged

2022-12-19 23:42 UTC, yeojiin commented on src/main/java/nextstep/subway/common/MaskingUtils.java
> +    private static final String MASK_EMAIL_PATTERN = "\\b(\\S+)+@(\\S+.\\S+)";
넵! 감사합니다~