step2 : 부하 테스트
next-step/infra-subway-monitoring pull request #690
Opened 2023-02-10 16:50 UTC by tndyd5390

그라파나가 뜨질 않아서 꽤나 고생했네요. 피드백 부탁드리겠습니다.

2023-02-11 16:26 UTC, brainbackdoor requested changes
2단계 미션 진행하느라 고생하셨어요~ 👍🏻 
몇가지 확인할 부분들이 있어서 Comment 남겨두었어요~ 
좋은 밤 보내세요~

2023-02-11 16:26 UTC, brainbackdoor commented on README.md
> +    - R : 5
스크립트를 보면, 로그인, 프로필 페이지와 경로찾기 기능 등 세번 요청하는 것으로 보이는데요. 왜 R이 5인가요?

2023-02-11 16:26 UTC, brainbackdoor commented on README.md
> +    - http_req_duration : 0.2
HTTP 응답시간을 200ms 를 목표로 두신 이유에 대해서도 남겨주시면 좋을거 같아요~
이전 미션에서 그냥 넘어갔어서요~ 

https://github.com/next-step/infra-subway-monitoring/pull/685/files

2023-02-11 16:26 UTC, brainbackdoor commented on README.md
> +    {duration: '1m', target: 16},
```suggestion
  stages: [
    {duration: '10s', target: 8},    
    {duration: '1m', target: 8},
    {duration: '10s', target: 16},    
    {duration: '1m', target: 16},
...    
```

- 목푯값으로 평소 트래픽과 피크타임 트래픽을 테스트하시려면 위와 같이 작성해야 해요~

2023-02-11 16:26 UTC, brainbackdoor commented on README.md
> +    http_req_duration: ['p(99)<1500'], // 99% of requests must complete below 1.5s
목표 응답시간이 200ms 로 설정하셨어요~

2023-02-11 16:26 UTC, brainbackdoor commented on README.md
> +    {duration: '2m', target: 100}
스트레스 테스트는 한계점까지 테스트를 해야 해요. 응답시간이 안정적인 것으로 보아 RPS를 더 높여도 될거 같아요~

2023-02-13 15:37 UTC, tndyd5390 commented on README.md
> +    - R : 5
제가 R의 의미를 잘못이해하고 있던것 같습니다. 프로세스의 수라고 이해하면 될까요?? 그러면 3으로 설정하면 되는 것일까요???

2023-02-13 15:46 UTC, tndyd5390 commented on README.md
> +    - http_req_duration : 0.2
서울 교통공사 길찾기가 500ms 정도 걸리기에 그의 절반 수준이 적당하다 생각하였습니다.

2023-02-14 19:23 UTC, brainbackdoor approved these changes
피드백 반영하느라 고생하셨어요~ 
추가로 Comment 들을 남겨두었는데요. 이 후 미션 진행하면서 반영바래요~

2023-02-14 19:23 UTC, brainbackdoor commented on README.md
> +    { duration: '2m', target: 500 }, // stay at 100 users for 10 minutes
```suggestion
    { duration: '1m', target: 1 }, // simulate ramp-up of traffic from 1 to 100 users over 5 minutes.
    { duration: '2m', target: 1 }, // stay at 100 users for 10 minutes
```

smoke test는 VUSer를 1 또는 2로 지정하고 테스트하는거에요~

2023-02-14 19:23 UTC, brainbackdoor commented on README.md
> +    http_req_duration: ['p(99)<1500'], // 99% of requests must complete below 1.5s
https://github.com/next-step/infra-subway-monitoring/pull/690#discussion_r1103654891

2023-02-14 19:23 UTC, brainbackdoor commented on README.md
> +    - 최대 VUser : 20 (40 * 2.5 / 5)
```suggestion
    - 평균 VUser : 16 (20 * 2.5 / 3)
    - 최대 VUser : 33 (40 * 2.5 / 3)
```
나눌때 R값도 변경되어야 해요;;

2023-02-14 19:23 UTC, brainbackdoor commented on README.md
> +    {duration: '10s', target: 20},
```suggestion
    {duration: '10s', target: 0},
```

2023-02-14 19:23 UTC, brainbackdoor commented on README.md
> +  let obj = http.get(`${BASE_URL}/paths/?source=1&target=7`, authHeaders).json();
경로찾기의 경우 값을 랜덤값으로 지정하셔야 해요~ 그래야 테스트가 의미가 있어져요
가령, 데이터캐싱을 할 경우, 2번째 이후로 보내는 요청은 현재로선 의미가 없어서요~

2023-02-14 19:23 UTC, merged