Step2 - 성능 테스트 리뷰 요청드립니다.
next-step/infra-subway-monitoring pull request #75
Opened 2021-07-03 12:18 UTC by dohchoi91

안녕하세요. 리뷰어님. 😄

서비스 진단하기 Step2 - 성능 테스트 완료하였습니다.

리뷰 부탁드립니다.

감사합니다. 🙇

2021-07-04 09:19 UTC, slamdunk7575 requested changes
테스트 하시느라 고생하셨어요 👍
몇가지 코멘트 남겨드렸습니다.
조금만 더 힘내주세요~!

2021-07-04 09:19 UTC, slamdunk7575 commented on README.md
> +    - `Effective use of CDN`
테스트한 결과를 통해 어떠한 개선을 할수 있을지 구체적으로 적어주면 좋을것 같아요.

```
예: 
gzip을 이용한 텍스트 압축 사용
사용하지 않는 자바스크립트 줄이기
정적 리소스 캐싱
```

2021-07-04 09:19 UTC, slamdunk7575 commented on script/load.js
> +  },
목표한 `Latency` 와 실제 테스트한 `Latency` 값이 다른데 둘중 하나를 맞춰주는게 좋겠네요.

2021-07-04 09:19 UTC, slamdunk7575 commented on script/load.js
> +    { duration: '10s', target: 0 }, // 사용자 0 명으로 감소
부하 테스트를 할때 `1일 평균 rps` 부터 `최대 rps` 에 대해 점차 테스트를 해보면 좋을것 같아요.

진행하면서 `최대 rps`를 충족하기 위한 `VUser`를 조절하면서 확인해보시면 좋겠어요.

2021-07-04 09:19 UTC, slamdunk7575 commented on script/load.txt
> +     http_req_failed................: 20.00%  ✓ 19710      ✗ 78840
`Stress 테스트`를 제외하고 나머지는 `http_req_failed` 가 0% 가 나와야 할 것 같아요.

위의 피드백을 참고해주세요.

2021-07-05 13:24 UTC, dohchoi91 commented
안녕하세요. 리뷰어님. 😄

리뷰 확인 하였습니다.
리뷰 주신 내용 토대로 수정 하였습니다.
다시 리뷰 부탁드립니다.  혹시 수정 방향이 다르다면 꼭 리뷰 다시 부탁드립니다.

감사합니다. 🙇

2021-07-06 03:48 UTC, slamdunk7575 approved these changes
고생 많으셨습니다 👍
소소한 코멘트 남겨드렸는데 참고해보시면 좋을 것 같아요.
남은 미션도 꾸준히 진행하시고 끝까지 완주하시길 응원하겠습니다~!

2021-07-06 03:48 UTC, slamdunk7575 commented on script/load.js
> +    http_req_duration: ['p(99)<3125'], // 99% of requests must complete below 3.125s
이부분에 목표한 `Latency`를 설정하는게 좋겠네요.
`latency : 50 ~ 100ms 이하`

2021-07-06 03:48 UTC, slamdunk7575 commented on script/stress.txt
> +     http_req_failed................: 20.00%  ✓ 12647      ✗ 50588
좀 더 정확히 느려지는 구간을 찾기 위해서 각 요청을 분리해서 테스트를 진행해보는 것도 좋을것 같아요.

2021-07-06 03:49 UTC, merged

2021-07-06 12:10 UTC, dohchoi91 commented
안녕하세요. 리뷰어님. 
머지는 되었지만, 한 가지 더 여쭤보고자 comment 남김니다.
이전 리뷰에서 다음과 같이 리뷰 주셨는데요.
https://github.com/next-step/infra-subway-monitoring/pull/75#discussion_r663472800

제가 이 부분을 잘못 이해한 것 같습니다. 😢 

제가 측정한 목표로 설정한 3 ~ 12rps대로 테스트를 한다면 
stage 당 1분(=60초) 잡았을 때 target을 20 ~ 5(VUser)로 잡고 테스트 하, latency가 목표로 잡은 50ms ~100ms 안에 테스트가 통과 되야 맞는건지요??

그렇게 되면 테스트의 옵션 값을 다음과 같이 설정해야하는 건가요??
```
export let options = {
  stages: [
    { duration: '1m', target: 20 }, // 1분 동안 사용자 1명에서 20명으로 증가하는 트래픽을 시뮬레이션합니다.
    { duration: '1m', target: 20 }, // 1분 동안 사용자 20명 유지
    { duration: '10s', target: 0 } // 사용자 0 명으로 감소
  ],
  thresholds: {
    http_req_failed: ['rate<0.01'],
    http_req_duration: ['p(99)<100'], // 99% of requests must complete below 100ms
    'logged in successfully': ['p(99)<100'], // 99% of requests must complete below 100ms
  }
};
```

2021-07-06 12:32 UTC, slamdunk7575 commented
네 맞습니다. 부하 테스트라는 것이 사용자가 몰렸을때 서버가 얼마나 견디는지 파악하고 대처하는 것이라

동현님이 목표로 잡으신 Latency를 아래처럼 설정하시고
`최대 rps`(http_reqs 확인)를 만족하기 위해서 부하를 조절하면서 테스트 해보면 좋겠다고 피드백 드렸던 것이였습니다. 

`http_req_duration: ['p(99)<100']`
latency 값은 대기시간으로 ‘이정도가 사용자가 느리지 않다고 판단한다.’ 라고 생각하시면 될것 같아요.

질문주신 부분에 제대로 답변을 드렸는지 모르겠네요 🙂