🚀 1단계 - 로깅과 모니터링
next-step/infra-subway-monitoring pull request #85
Opened 2021-07-04 17:30 UTC by fDevJc

안녕하세요 리뷰어님!
경험이 없다보니 엄청어렵네요 ㅠㅠ
많은 피드백 부탁드리겠습니다.
감사합니다.

2021-07-05 13:23 UTC, kingbbode requested changes
코멘트 작성해두었습니다.
확인 부탁드려요 :)

2021-07-05 13:23 UTC, kingbbode commented on README.md
>  1. 각 서버내 로깅 경로를 알려주세요
안녕하세요 :)
로거 설정에 대한 xml 파일이 보이지 않네요!
확인 부탁드립니다.

2021-07-05 16:07 UTC, fDevJc commented on README.md
>  1. 각 서버내 로깅 경로를 알려주세요
안녕하세요 서비스 진단하기 1차과제 진행중인 양지철입니다
혹시 피드백 주신 내용 : infra-subway-monitoring/src/main/resources/config/
해당경로의 로깅경로 설정한거 외에 따로 appender를 안만들었느냐가 맞을까요??

2021-07-09 16:51 UTC, kingbbode approved these changes
확인했습니다 :)
머지하겠습니다.

2021-07-09 16:51 UTC, merged